### ISSUE TITLE
Error Trying To Load Tool in Calibre

### ISSUE THREAD

**Issue by abrogard** [apprenticeharper/DeDRM_tools#1257] opened 2020-09-28 23:19 UTC
I just downloaded/installed Calibre and then I got the tool and tried to put it in Calibre.
Got this:
calibre, version 5.0.1
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.0.1  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 202, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax
Not sure if calibre is at fault or the tool.  need help.   :)   ?

**Comment by SunnyJames** [comment] 2020-09-28 23:29
Plugin appears to work with Calibre 4.23.0 but not 5.x

**Comment by ElleKayEm** [comment] 2020-09-28 23:29
DeDRM 6.8 is not compatible with calibre 5.  You will need to stick with calibre 4.23 until the next update of DeDRM.  Work on this is ongoing.

**Comment by abrogard** [comment] 2020-09-29 00:28
Ah...  so..  thank you very much, guys.   :)

**Comment by tartley** [comment] 2020-10-21 00:50
Closing this for now, as a dupe of https://github.com/apprenticeharper/DeDRM_tools/issues/1324.

**Closed by tartley** 2020-10-21 00:50 UTC
