### ISSUE TITLE
DeDRM 10.0.3 fail in Calibre 6.14

### ISSUE THREAD

**Issue by zmixnyc** [apprenticeharper/DeDRM_tools#2217] opened 2023-03-18 21:31 UTC
calibre, version 6.14.0
ERROR: Loading book failed: Failed to open the book at [ book path ]

Failed to convert book: [book name]  with error:
DeDRM v10.0.3: Trying to decrypt [book name] .epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Post-processing took 0.0 seconds
DeDRM v10.0.3: Finished after 0.2 seconds
InputFormatPlugin: EPUB Input running
on /var/folders/88/0g82_jxd13s_wkhbgwjc40lw0000gn/C/calibre_6.14.0_tmp_kodin_pd/fg19akgb.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 41, in <module>
  File "site.py", line 37, in main
  File "calibre/utils/ipc/worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre/srv/render_book.py", line 821, in viewer_main
  File "calibre/srv/render_book.py", line 812, in render_for_viewer
  File "calibre/srv/render_book.py", line 790, in render
  File "calibre/srv/render_book.py", line 613, in process_exploded_book
calibre.srv.render_book.Spineless: Book is empty, no content in spine

**Comment by ElleKayEm** [comment] 2023-03-18 22:15
This log doesn't really doesn't tell us anything.  What type of DRM?

**Comment by zmixnyc** [comment] 2023-03-18 22:45
Sorry, what can I provide that will be helpful?

**Comment by ElleKayEm** [comment] 2023-03-18 22:57
Where is it from?  How did you download it?

**Comment by zmixnyc** [comment] 2023-03-18 22:59
Adobe Digital Editions

**Comment by zmixnyc** [comment] 2023-03-18 23:00
I can open the epub file on an old computer and use "DeDRM 1.8" app and read it on that computer - but when I put it in my eReader is cannot be opened.

**Comment by ElleKayEm** [comment] 2023-03-18 23:12
Is ADE that you used to download it on the same machine and user as calibre with DeDRM?  Is it authorized with your Adobe ID?

**Comment by zmixnyc** [comment] 2023-03-18 23:14
Yes it's the same machine and user.  Do I need to authorize Calibre (or the DeDRM 10.0.3 plugin) with my adobe ID?

**Comment by ElleKayEm** [comment] 2023-03-18 23:24
No, I meant is Adobe Digital Editions authorized with an Adobe ID?

**Comment by zmixnyc** [comment] 2023-03-18 23:30
Yes ADE is authorized and has no problems downloading and fulfilling the epub book

**Comment by ElleKayEm** [comment] 2023-03-18 23:39
Alright, let's try looking at a log of adding the book to calibre: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by zmixnyc** [comment] 2023-03-19 00:55
Thank you for the advice, here is the resultant log:


Using calibre Qt style: True
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
calibre Debug log
calibre 6.14  embedded-python: True
macOS-12.5.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.5.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Annotations (1, 17, 13) && KOReader Sync (0, 4, 1) && Obok DeDRM (10, 0, 3) && PocketBook632 (1, 0, 2) && Pocketbook Tools (0, 9, 6)
calibre 6.14  embedded-python: True
macOS-12.5.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.5.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Annotations (1, 17, 13) && KOReader Sync (0, 4, 1) && Obok DeDRM (10, 0, 3) && PocketBook632 (1, 0, 2) && Pocketbook Tools (0, 9, 6)
QPA platform: cocoa
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 109.00000163701577 x 109.00000163701577
[0.00] Starting up...
[0.02] Showing splash screen...
[0.21] splash screen shown
[0.21] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
DEBUG:    0.0 Annotations plugin: Error loading libiMobileDevice. This hasn't worked for a while, and is blacklisted in calibre v3.
DEBUG:    0.0 Annotations plugin: Error is:  No module named 'calibre.devices.idevice'
DEBUG:    0.0 Annotations::reader_app_support.py - loading translations
DEBUG:    0.0 Annotations::common_utils.py - loading translations
DEBUG:    0.0 Annotations::appearance.py - loading translations
DEBUG:    0.0 Annotations::config.py - loading translations
DEBUG:    0.0 Annotations::annotated_books.py - loading translations
DEBUG:    0.1 Annotations::action.py - loading translations
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
DEBUG:    0.5 koreader:action:KoreaderAction:genesis:start
[1.67] main UI initialized...
[1.67] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Dying Inside.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Dying Inside.epub is a secure Adobe Adept ePub for UUID 5f93a002-0ebb-4c14-9fe2-b37ff016f717
DeDRM v10.0.3: Trying UUID-matched encryption key default_ade_key_uuid_5f93a002-0ebb-4c14-9fe2-b37ff016f717_AdobeID_[redacted]
ratnrm_c.epub is a secure Adobe Adept ePub.
DeDRM v10.0.3: Decrypted with key default_ade_key_uuid_5f93a002-0ebb-4c14-9fe2-b37ff016f717_AdobeID_[redacted]
after 0.3 seconds
DeDRM v10.0.3: Post-processing took 0.0 seconds
DeDRM v10.0.3: Finished after 0.3 seconds
[11.93] splash screen hidden
[11.93] Started up in 11.93 seconds with 292 books

Debugging DND event
text/uri-list 69 b'file:///Users/[redacted]/Documents/Digital%20Editions/Dying%20Inside.epub\r\n' 


Firefox rurl: None None
URLS: ['file:///Users/[redacted]/Documents/Digital%20Editions/Dying%20Inside.epub']
Paths: ['/Users/[redacted]/Documents/Digital Editions/Dying Inside.epub']
Extensions: frozenset({'epub'})
Added Dying Inside to db in: 0.0
Added 1 books in 1.0 seconds
Worker Launch took: 0.01 seconds

**Comment by ElleKayEm** [comment] 2023-03-19 08:51
This log shows the book is decrypted.  So there must be something about it that your ereader doesn't like.  Can it be opened with the calibre ebook viewer?

**Comment by zmixnyc** [comment] 2023-03-19 12:03
When I try to open it in Calibre 's ebook viewer it generates the error pasted into my original post..

**Comment by ElleKayEm** [comment] 2023-03-19 13:00
Oh, yes, sorry.  There seems to be something incorrect or at least something unusual about the structure of that book.  But the issue doesn't seem to be DRM.

**Comment by zmixnyc** [comment] 2023-03-19 13:07
What is particularly strange, then, is that it opens just fine in Calibre 3.48 on my old macbook..  any ideas?

**Comment by zmixnyc** [comment] 2023-03-19 13:20
EDIT: I opened the book in Calibre 3.48 and "converted" the original .epub to .epub - *that* version opens fine in my eReader..    strange, but 'solved'...?

**Comment by ElleKayEm** [comment] 2023-03-19 13:55
And that definitely confirms that DRM wasn't the issue since you can't convert a book with DRM.

**Comment by zmixnyc** [comment] 2023-03-19 13:57
Still wondering why it does not work in Calibre 6.14?

**Comment by ElleKayEm** [comment] 2023-03-19 14:02
Don't know.  Guess the calibre viewer is less forgiving now.

**Comment by zmixnyc** [comment] 2023-03-19 14:03
I'll continue testing...

**Comment by ElleKayEm** [comment] 2023-03-19 14:23
Since the problem isn't related to DeDRM, you can close this issue.  You can still comment or reopen later if needed.

**Comment by zmixnyc** [comment] 2023-03-19 14:41
Will do.  Thank you for all your help.

**Closed as completed** 2023-03-19 14:42 UTC
