### ISSUE TITLE
Failed Convert From Kindle For PC AZW

### ISSUE THREAD

**Issue by whitesnowowl** [apprenticeharper/DeDRM_tools#192] opened 2017-01-30 12:09 UTC
The book has failed to convert in the Calibre for all the day . Please let me know what's wrong with it .
Processor  intel i7 
Windows 10 64-bit
16 GB RAM

The log file:

C:\WINDOWS\system32>calibre-debug -g
calibre 2.78 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 127.664921466 x 127.590697674
Starting up...
Started up in 2.05 seconds with 339 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xf5$\xf3\x05\xf4\xe2\xbf\xb4\xd3-"\x0ex\x15\xef\xcfY\x19\xd5\x1e\xee\x9f\xf5\x90\xb0\xb3\xaa\xac\xab\x0c\xa8\x07', 'C:\\Users\\\xe8\xb5\xb5\xe5\x86\x89\\Documents\\My Kindle Content\\B01D9O07OC_EBOK.azw']
DeDRM v6.5.3: Trying to decrypt B01D9O07OC_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright �� 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: ������������������������������������������������ (���������������������������)
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '741343209' and UserName '7589'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright �� 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: ������������������������������������������������ (���������������������������)
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 168, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds
C:\Program Files\Calibre2\pylib.zip\dateutil\parser.py:339: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added 硬派健身：臀腿训练：知乎斌卡作品 (知乎「一小时」系列) to db in: 0.3
Added 1 books in 0.8 seconds
Worker Launch took: 0.1859998703

**Comment by ElleKayEm** [comment] 2017-01-31 01:08
Was the book downloaded with the current installation of Kindle for PC on the same machine and user as calibre?

**Comment by whitesnowowl** [comment] 2017-01-31 02:09
Yes，it's the same machine and user.

**Comment by ElleKayEm** [comment] 2017-01-31 02:31
Try looking at this part of the FAQs:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-have-installed-the-calibre-plugin-and-the-book-is-not-already-in-calibre-but-the-drm-does-not-get-removed-it-is-a-kindle-book

**Comment by whitesnowowl** [comment] 2017-01-31 15:04
All the steps I have done. It still can not convert. I will try on my another pc the next day. Thank you  for giving my advice.

**Comment by ElleKayEm** [comment] 2017-01-31 18:18
If your Windows user name doesn't have non-ASCII characters and you've tried the steps for reinstalling Kindle for PC, then I don't know what the problem is.

**Comment by whitesnowowl** [comment] 2017-02-01 03:14
I GOT IT. My windows user name is Chinese characters. The issure has be solved. THANKS A LOT.

**Comment by ElleKayEm** [comment] 2017-02-01 22:48
Wonderful!  Go ahead and close this issue.

**Closed** 2017-02-02 03:05 UTC
