### ISSUE TITLE
Cannot remove DRM from pdfs

### ISSUE THREAD

**Issue by klinkehoffen** [apprenticeharper/DeDRM_tools#1284] opened 2020-10-06 06:02 UTC
Hi there,
Since the latest update of Calibre (calibre-5.1.0), I can no longer remove the DRM from pdfs from the Internet Archive, so am stuck using the crap Adobe reader. Can you advise if there is a patch or an update coming? 

I add the file into Calibre OK, but when I click on it, I get an message "The document requires digital rights management (DRM) supported by Adobe Digital Editions. Would you like to open it in Digital Editions now?"

**Comment by pengtsin** [comment] 2020-10-06 17:09
FYI ... I filed a bug with Calibre and got this response ... (Calibre 4.23 is the last version that supports DeDRM v6.8.0.)

As of calibre 5, calibre has moved from Python 2 to Python 3, because Python 2 has been end-of-lifed.
This means that some third party calibre plugins that have not yet been ported to Python 3 will not work
with calibre 5. If you depend on such a plugin, you will have to either:

Wait for the plugin to be ported to Python 3
If you are on windows, you can install the last calibre 4.x release using calibre portable and
run the plugin there
Downgrade to calibre 4.x until the plugin is ported. You can simply uninstall calibre 5 and install calibre 4.23, doing so
will not affect your books or settings.

**Comment by klinkehoffen** [comment] 2020-10-06 18:15
Thanks so much, pengstin. Rolled back to 4.21.

**Comment by ElleKayEm** [comment] 2020-10-07 03:10
Work is in progress to make DeDRM compatible with calibre 5.x.

**Comment by klinkehoffen** [comment] 2020-10-07 17:06
> Work is in progress to make DeDRM compatible with calibre 5.x.
Thanks ElleKayEm!

**Comment by tartley** [comment] 2020-10-20 21:21
Closing this issue for now, as a dupe of https://github.com/apprenticeharper/DeDRM_tools/issues/1324.  Shout if that's not right.

**Closed by tartley** 2020-10-20 21:21 UTC

**Comment by klinkehoffen** [comment] 2020-10-21 03:42
Thanks for letting me know, Jonathan – much appreciated.

Sam Young
________________________
tel                  + 64 27 244 7154
e:mail          sam@samyoung.co.nz<mailto:sam@samyoung.co.nz>
