### ISSUE TITLE
SyntaxError:invalid syntax(calibre_plugins.dedrm__init__, line 168)

### ISSUE THREAD

**Issue by mjharmstone** [apprenticeharper/DeDRM_tools#1304] opened 2020-10-10 20:20 UTC
Hi,

I'm trying to install DeDRM on Calibre 5.2.0, but getting the above error code. I've unzipped the file and am trying to add the DeDRM_Plugin.zip file. This is the log:
calibre, version 5.2.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.2  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', 'SP0', 'Multiprocessor Free')
Interface language: en_GB
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 282, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 174, in exec_module
  File "calibre\customize\zipplugin.py", line 170, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by paapereira** [comment] 2020-10-10 20:48
I'm having the same issue.

```bash
calibre, version 5.2.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.2  embedded-python: False is64bit: True
Linux-5.8.14-arch1-1-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.8.14-arch1-1', '#1 SMP PREEMPT Wed, 07 Oct 2020 23:59:46 +0000')
Python 3.8.6
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && Package KFX (from KFX Input) (1, 34, 0) && Goodreads (1, 5, 1) && Goodreads Sync (1, 14, 3) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Prettify Cover (1, 5, 0)
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 317, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 282, in load
    m = importlib.import_module(plugin_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 174, in exec_module
    compiled = self.get_code()
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 170, in get_code
    return compile(self.get_source_as_bytes(fullname), f'calibre_plugins.{self.plugin_name}.{self.fullname_in_plugin}',
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax
```

**Comment by l-l-l-l-l-l** [comment] 2020-10-10 21:34
Latest stable release 6.8.0 is written in Python 2, which is no longer supported by Calibre 5, while version 7.0, which is still being worked on, has its flaws. You'll have to either wait for the release of the complete version 7.0 or downgrade your calibre to 4.23.

**Comment by dampertable800** [comment] 2020-10-12 05:48
I just downloaded Calibre 4.23.  Added 6.8 plugin, and still getting an error when converting from an .azw3 file

**Comment by dagware** [comment] 2020-10-12 12:23
Any guess as to when 7.0 will be out? No pressure - just wondering if you had a ballpark idea. Thanks.

**Comment by Tuuure** [comment] 2020-10-13 09:35
I had the same issue. But it's difficult to downgrade Calibre on Arch Linux. So I download the latest source code and generate zip files using **make_release.py**. It works fine with Calibre 5.2.0 as far as I can tell.

**Comment by dampertable800** [comment] 2020-10-14 16:50
Where did you find the make_release.py file? Thank you.

**Comment by tartley** [comment] 2020-10-20 21:04
Closing as dupe of https://github.com/apprenticeharper/DeDRM_tools/issues/1324

**Closed by tartley** 2020-10-20 21:04 UTC
Labels: duplicate, install-fail, python3-syntax

**Comment by ElleKayEm** [comment] 2020-11-19 13:05
@dampertable800 
DRM removal happens when you first add the book to calibre, not during conversion.  Here's how to get a log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

make_release.py is part of [the source code here](https://github.com/apprenticeharper/DeDRM_tools).

**Comment by ElleKayEm** [comment] 2020-11-19 13:09
> Any guess as to when 7.0 will be out? No pressure - just wondering if you had a ballpark idea. Thanks.

Nope.  This is an all-volunteer community project so it will be done when it's done.
