### ISSUE TITLE
DeDRM v6.6.1: Ultimately failed to decrypt

### ISSUE THREAD

**Issue by RemmyBailey** [apprenticeharper/DeDRM_tools#629] opened 2018-09-13 21:31 UTC
removed kindle for PC, deleted all directories, reinstalled, re-registered device, but still can't decrypt

calibre Debug log
calibre 3.31 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 8, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 8, 0) && KFX metadata reader (from KFX Input) (1, 8, 0) && KFX Input (1, 8, 0)
calibre 3.31 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 8, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 8, 0) && KFX metadata reader (from KFX Input) (1, 8, 0) && KFX Input (1, 8, 0)
Not controlling automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.42] splash screen shown
[0.42] Initializing db...
[0.45] db initialized
[0.45] Constructing main UI...
[2.53] main UI initialized...
[2.53] Hiding splash screen
[5.61] splash screen hidden
[5.61] Started up in 5.61 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['-\x8dB\x12\xa5#\x94\xb3\xcbR"\x18E\xa5\x90\rp!\xe4\xd5t\xde4\xefr\'\xa3\xa0\x16\x9e\xa1$', 'C:\\Users\\bg\\Documents\\My Kindle Content\\B00KVOJBHS_EBOK\\B00KVOJBHS_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.8.0: Importing C:\Users\bg\Documents\My Kindle Content\B00KVOJBHS_EBOK\B00KVOJBHS_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 3 file(s) as C:\Users\BG1\AppData\Local\Temp\calibre_6dtjlx\79eoxe.kfx-zip
DeDRM v6.6.1: Trying to decrypt 79eoxe.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: 79eoxe
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.bc43e542-214e-4575-8b6f-6ecc7d65216d.voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\bg\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\bg\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2789240566' and UserName '42476f73736572616e64'
DeDRM v6.6.1: Found 1 new key
Decrypting KFX-ZIP ebook: 79eoxe
Got DSN key from database default_key_1
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.bc43e542-214e-4575-8b6f-6ecc7d65216d.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.8.0: Packaging C:\Users\BG\AppData\Local\Temp\calibre_6dtjlx\79eoxe.kfx-zip
Processing container: B00KVOJBHS_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 76, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 149, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 260, in get_container
KFXDRMError: Book container B00KVOJBHS_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\BG\AppData\Local\Temp\calibre_6dtjlx\_3fm5l_add_books\0\B00KVOJBHS_EBOK.kfx-zip
Added Records: Vol. 4 1820-1829 to db in: 0.3
Added 1 books in 1.6 seconds

**Comment by j-howell** [comment] 2018-09-13 23:32
Unfortunately the ultimate cause of the error does not appear in that log because there were two failures and only the reason for the first (missing key from your K4PC install) one was reported. 

Most likely the second failure was caused by trying to remove DRM from a book that is on loan to you. These tools are intended for use on purchased books.

Now that DeDRM has the proper key to use, if you try to import that book again the log should show the true reason for the failure.

**Comment by RemmyBailey** [comment] 2018-09-14 00:00
You're right, I didn't realize this was as KindleUnlimited book.
Once I imported a different book that decoded correctly, I tried to re-import the bad book and it threw up the real error 
DeDRM v6.6.1: Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.

Is the encryption different for loaned content vs purchased content?
I'm just wondering it intentionally doesn't decrypt loaned content because the end user didn't purchase it.  That would make sense.

**Comment by j-howell** [comment] 2018-09-14 01:18
It is intentional. No Help with DRM removal of non-purchased books will be given here.

**Comment by RemmyBailey** [comment] 2018-09-14 13:05
Totally agree.  Thanks for the help.
You can close this

**Comment by ElleKayEm** [comment] 2018-09-14 13:43
As the person who opened the issue, you're the one who can close it.

**Closed** 2018-09-14 13:54 UTC
