### ISSUE TITLE
Calibre 5.2 does not work

### ISSUE THREAD

**Issue by JuanZarAlbe** [apprenticeharper/DeDRM_tools#1303] opened 2020-10-10 18:56 UTC
I have just tried to de-DRM-ized a Kindle Book.
I got it with Kindle for PC 1.16.
I have 6.7 tools.
I have 5.2 Calibre.
I couldn't do it, until I switched to Calibre 4.23. Then I could.
What must I do? Not updating Calibre, nor tools? I know that actual tools are 6.8.

**Comment by tartley** [comment] 2020-10-11 02:01
DeDRM releases currently only work with Calibre v4.xx.
People are working at updating DeDRM to work with Calibre 5, but it will take a little while (weeks?). When it is done, there will be a new release.

**Comment by josteink** [comment] 2020-10-12 18:51
Great to hear it being worked on.

And as someone who has tried to port code from Python 2 to Python 3 before, you have my fullest sympathies. Take whatever time you need! :smile:

**Comment by wolfkin** [comment] 2020-10-14 03:27
See also #979 and #1192

**Comment by tartley** [comment] 2020-10-20 21:05
Closing as a dupe of https://github.com/apprenticeharper/DeDRM_tools/issues/1324

**Closed by tartley** 2020-10-20 21:05 UTC
