### ISSUE TITLE
Cannot load DeDRM_Plugin.zip on Calibre 4.99.5 on Debian testing

### ISSUE THREAD

**Issue by yasbean** [apprenticeharper/DeDRM_tools#1097] opened 2020-05-17 21:40 UTC
When I try to load 6.7.0, I get the following error:

calibre, version 4.99.5
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 4.99.5  embedded-python: False is64bit: True
Linux-5.6.0-1-amd64-x86_64-with-glibc2.29 Linux ('64bit', 'ELF')
('Linux', '5.6.0-1-amd64', '#1 SMP Debian 5.6.7-1 (2020-04-29)')
Python 3.8.3
Interface language: None
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 319, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 200, in load
    reload(m)
  File "/usr/lib/calibre/polyglot/builtins.py", line 123, in reload
    return importlib.reload(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 602, in _exec
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 179, in load_module
    compiled = compile(code, 'calibre_plugins.%s.%s'%(plugin_name,
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment] 2020-05-17 22:08
Not working with Python 3 yet.

**Comment by oakreef** [comment] 2020-05-21 17:40
I'm experiencing the same issue. Is there any workaround?

**Comment by ElleKayEm** [comment] 2020-05-21 18:32
Use a version of calibre with Python 2.

**Comment by oakreef** [comment] 2020-05-21 18:53
Do you know what version Calibre moved to requiring Python 3 for plugins in? I am having trouble finding this information.

**Comment by ElleKayEm** [comment] 2020-05-21 19:59
I believe the latest release at calibre-ebook.com still has Python 2.  Someone else in one of these issues also suggested this:

https://flathub.org/apps/details/com.calibre_ebook.calibre

**Comment by foobnix** [comment] 2020-05-22 14:03
The same issue with the latest Ubuntu 20.04

**Comment by ub2004** [comment] 2020-05-24 15:15
please take a look at - https://github.com/apprenticeharper/DeDRM_tools/issues/1090

My working config for Ubuntu 20.04 relies on Wine and old windows packages.

ActivePython-2.7.8.10-win32-x86.msi
pycrypto-2.1.0.win32-py2.7.exe
KindleForPC-installer-1.17.44170.exe
calibre-2-80-0.msi

**Comment by tartley** [comment] 2020-10-21 03:01
Closing as a dupe of https://github.com/apprenticeharper/DeDRM_tools/issues/1324

**Closed by tartley** 2020-10-21 03:01 UTC
