### ISSUE TITLE
Calibre Plugin DeDRM 6.6.1 Install Failure

### ISSUE THREAD

**Issue by dlfuller** [apprenticeharper/DeDRM_tools#571] opened 2018-07-06 15:02 UTC
My attempts to install the new DeDRM 6.6.1 Plugin into Calibre are met with: InvalidPlugin: The plugin in u'/Users/dlfuller/Downloads/DeDRM_tools_6.6.1.zip' is invalid. It does not contain a top-level __init__.py file

MY APOLOGIES.  From my memory of last time, I was looking for a plugin zip to install.  And, did not realize the need to unzip the tools and then find the plugin zip inside of DeDRM_calibre_plugin.  Successfully installed without a hitch.  NO INSTALL FAILURE.

**Comment by ElleKayEm** [comment] 2018-07-06 15:24
You're trying to install the whole archive.  Unzip that file and look in the DeDRM_calibre_plugin folder for DeDRM_plugin.zip

**Comment by clholley** [comment] 2018-08-04 23:06
I'm having a similar problem. I downloaded Calibre and then downloaded DeDRM_tools_6.6.1.zip and unzipped it. Then clicked on DeDRM_calibre_plugin and DeDrm_plugin and clicked on the Extract All button. Then I get lost. The website https://www.makeuseof.com/tag/remove-drm-every-ebook-own/ said to open Calibre, click on Preferences, Plug Ins, and then Load plug in from file. I opened DeDRM_calibre_plugin > DeDRM_plugin and saw a zipped file called allcrypto_src. When I tried to unzip this file, I got an error message saying it does not contain a top-level init.py file. I ended going into File Explorer and found this file and unzipped it. Then went back to Calibre > Preferences >Plug Ins > Load plug in from file. I navigated to DeDRM_calibre_plugin > DeDRM plugin > allcrypto_src which has an empty file called allcrypto_src. Totally stumped at this point. The only reason I'm trying to do all this is because of stories about ebook sellers that suddenly decide to delete a user's entire library. I just want to be able to save my favorite books so I don't lose them.

**Comment by ElleKayEm** [comment] 2018-08-04 23:24
Only extract DeDRM_tools_6.6.1.zip.  Stop right there and don't extract anything else.  When loading into calibre, look inside the DeDRM_calibre_plugin folder and select DeDRM_plugin.zip.

**Comment by gros-chat** [comment] 2020-10-29 10:36
I am using calibre 5.3 and dedrm 6.8 with windows. I had the same problem. It seems that calibre is requesting a file when it needs a folder. I have zipped all the files in DeDRM_plugin and zipped them back. For some reasons it worked. I have tried to zip the files in DeDRM_plugin directly, it did not work. So I have no real understanding of the question. Just try to rezipp some files

**Comment by tartley** [comment] 2020-10-29 12:38
@gros-chat: All DeDRM releases (such as 6.8) only work with Calibre version 4.x.  You must downgrade Calibre to use DeDRM.

No re-zipping of files is required. Calibre needs the file "DeDRM_plugin.zip"

**Comment by tartley** [comment] 2020-10-29 12:40
Duplicate of #554

**Closed by tartley** 2020-10-29 12:40 UTC
Labels: docs, duplicate, install-fail

**Comment by gros-chat** [comment] 2020-10-30 04:38
@tartley 
I have this message tho when i use version <5. That the opposite, i am asked to upgrade...

![dedrm](https://user-images.githubusercontent.com/15571242/97660473-a4696600-1aac-11eb-9f2f-ad48803a853e.png)

**Comment by gros-chat** [comment] 2020-10-30 04:42
@tartley 

I get this message when i use DeDRM with versions of Calibre < 5
![dedrm2](https://user-images.githubusercontent.com/15571242/97660732-6882d080-1aad-11eb-8a9f-cfebe6024fa1.png)

**Comment by ElleKayEm** [comment] 2020-11-28 21:34
Is it the regular release of calibre 4.23?  Or one that came with a distro package which has Python 3?

**Comment by ElleKayEm** [comment] 2020-11-28 21:37
Or are you trying to load one of the pre-releases of DeDRM 7 which needs calibre 5?  Or the master branch?
