### ISSUE TITLE
cannot import DeDRM into Calibre

### ISSUE THREAD

**Issue by qveinole** [apprenticeharper/DeDRM_tools#1288] opened 2020-10-08 02:25 UTC
I just upgraded my calibre to 5.2, but i found that DeDRM wouldn't work with that, so i checked the issues and downgraded calibre to 4.23. BUT i still cannot import DeDRM into calibre...

calibre, version 4.23.0
错误： 未处理的异常: <b>InvalidPlugin</b>:The plugin in u'/Users/apple/Downloads/DeDRM_tools_6.8.0 (1).zip' is invalid. It does not contain a top-level __init__.py file

calibre 4.23  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: zh_CN
Successfully initialized third party plugins: EpubSplit (2, 9, 0) && KindleUnpack - The Plugin (0, 82, 3)
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 472, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 61, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 194, in load
  File "site-packages/calibre/customize/zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'/Users/apple/Downloads/DeDRM_tools_6.8.0 (1).zip' is invalid. It does not contain a top-level __init__.py file

**Comment by suint** [comment] 2020-10-08 03:40
You have to open that .zip file, then import the file called "DeDRM_plugin.zip"

That being said, I had the same issue, and once I did the above, I got this:

calibre, version 5.2.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.2  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 282, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 174, in exec_module
  File "calibre\customize\zipplugin.py", line 170, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by qveinole** [comment] 2020-10-08 05:28
> You have to open that .zip file, then import the file called "DeDRM_plugin.zip"
> 
> That being said, I had the same issue, and once I did the above, I got this:
> 
> calibre, version 5.2.0
> ERROR: Unhandled exception: SyntaxError:invalid syntax (calibre_plugins.dedrm.**init**, line 168)
> 
> calibre 5.2 embedded-python: True is64bit: False
> Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
> 32bit process running on 64bit windows
> ('Windows', '10', '10.0.19041')
> Python 3.8.5
> Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
> Interface language: None
> Traceback (most recent call last):
> File "calibre\gui2\preferences\plugins.py", line 317, in add_plugin
> File "calibre\customize\ui.py", line 472, in add_plugin
> File "calibre\customize\ui.py", line 61, in load_plugin
> File "calibre\customize\zipplugin.py", line 282, in load
> File "importlib__init__.py", line 127, in import_module
> File "", line 1014, in _gcd_import
> File "", line 991, in _find_and_load
> File "", line 975, in _find_and_load_unlocked
> File "", line 671, in _load_unlocked
> File "calibre\customize\zipplugin.py", line 174, in exec_module
> File "calibre\customize\zipplugin.py", line 170, in get_code
> File "calibre_plugins.dedrm.**init**", line 168
> print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
> ^
> SyntaxError: invalid syntax

thx！

**Comment by alexbaxter** [comment] 2020-10-08 07:40
I'm getting a similar issue on macOS `10.15.7` when trying to load the `6.8.0` version of the plugin `DeDRM_Plugin.zip` into Calibre `5.2.0`. Maybe a python version incompatibility?

```
calibre, version 5.2.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.2  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "calibre/customize/ui.py", line 472, in add_plugin
  File "calibre/customize/ui.py", line 61, in load_plugin
  File "calibre/customize/zipplugin.py", line 282, in load
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 174, in exec_module
  File "calibre/customize/zipplugin.py", line 170, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

```

**Comment by SamMorrowDrums** [comment] 2020-10-08 08:48
@alexbaxter yes - there hasn't been a python 3 release yet. There is lots of work in progress, and there have been PRs merged over the last couple of weeks. You can (if you can work out how to install from source), use the master branch version of the plugin - which should *mostly* work, but obviously it's not yet an official release.

**Comment by alexbaxter** [comment] 2020-10-08 08:56
> @alexbaxter yes - there hasn't been a python 3 release yet. There is lots of work in progress, and there have been PRs merged over the last couple of weeks. You can (if you can work out how to install from source), use the master branch version of the plugin - which should _mostly_ work, but obviously it's not yet an official release.

Could I downgrade to the previous version of Calibre?

**Comment by SamMorrowDrums** [comment] 2020-10-08 09:12
Yes downgrade should work well. And it should be at most a few weeks until
a release judging by development speed.

**Comment by rmathot** [comment] 2020-10-08 09:48
An experimental branch is available there: https://github.com/apprenticeharper/DeDRM_tools/issues/1278#issuecomment-705180984

**Comment by peterwjsinclair** [comment] 2020-10-09 03:18
I have been getting the same problem as alexbaxter on same platform (macOS 10.15.7, Calibre 5.2). I cloned the master github repo and reran "./make_release.py 6.8.0" (I'm at python 3.8.5) then unzipped DeDRM_tools_6.8.0.zip and loaded the DeDRM_plugin.zip file into Calibre. I was then able to convert a Digital Editions epub to mobi.

**Comment by JoergSchumann3141** [comment] 2020-10-09 21:43
> I have been getting the same problem as alexbaxter on same platform (macOS 10.15.7, Calibre 5.2). I cloned the master github repo and reran "./make_release.py 6.8.0" (I'm at python 3.8.5) then unzipped DeDRM_tools_6.8.0.zip and loaded the DeDRM_plugin.zip file into Calibre. I was then able to convert a Digital Editions epub to mobi.

Worked for me (same platform) as well for EPUBs, but not for PDFs.

**Comment by tartley** [comment] 2020-10-20 21:14
Closing as a dupe of https://github.com/apprenticeharper/DeDRM_tools/issues/1324

**Closed by tartley** 2020-10-20 21:14 UTC
