### ISSUE TITLE
Plugin wont install on Calibre 5.0.1

### ISSUE THREAD

**Issue by RZRZR** [apprenticeharper/DeDRM_tools#1264] opened 2020-09-30 10:33 UTC
on Mac

calibre, version 5.0.1
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.0.1  embedded-python: True is64bit: True
macOS-10.15.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.6', ('', '', ''), 'x86_64')
Interface language: en_GB
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 472, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 61, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 200, in load
  File "site-packages/polyglot/builtins.py", line 123, in reload
  File "lib/python3.8/importlib/__init__.py", line 169, in reload
  File "<frozen importlib._bootstrap>", line 602, in _exec
  File "site-packages/calibre/customize/zipplugin.py", line 179, in load_module
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment] 2020-09-30 10:48
DeDRM 6.8 is not compatible with calibre 5.  You will need to use calibre 4.23 until the next release of DeDRM.

**Comment by hamkg** [comment] 2020-10-01 18:37
See https://github.com/apprenticeharper/DeDRM_tools/issues/979#issuecomment-700960177
This solution seems to work at least for kindle and epub, windows and linux.

**Comment by odysseus654** [comment] 2020-10-03 08:18
I tried it (before finding this note) and it looks like things went into an infinite loop trying to add a book.  I might try to poke at it again in a day or so.

**Comment by ElleKayEm** [comment] 2020-10-03 09:08
@odysseus654 
If you're on Windows, are you using 64-bit calibre?

**Comment by odysseus654** [comment] 2020-10-04 02:08
Yes, currently running Calibre 5.1 [64bit]

**Comment by tartley** [comment] 2020-10-20 21:48
Closing as a dupe of https://github.com/apprenticeharper/DeDRM_tools/issues/1324

**Closed by tartley** 2020-10-20 21:48 UTC
