### ISSUE TITLE
Calibre won't install DeDRM 6.8.0 on calibre, version 5.3.0

### ISSUE THREAD

**Issue by jasen2339** [apprenticeharper/DeDRM_tools#1324] opened 2020-10-18 07:11 UTC
calibre, version 5.3.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.3  embedded-python: True is64bit: True
macOS-10.15.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Obok DeDRM (6, 7, 0)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "calibre/customize/ui.py", line 472, in add_plugin
  File "calibre/customize/ui.py", line 61, in load_plugin
  File "calibre/customize/zipplugin.py", line 285, in load
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 177, in exec_module
  File "calibre/customize/zipplugin.py", line 173, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by MikeHg** [comment] 2020-10-18 08:39
See #1303, #979 and #1192 

DeDRM releases currently only work with Calibre v4.xx. Work for supporting Calibre5 is under way

**Comment by yiyi0724** [comment] 2020-10-19 07:36
快点修复吧

**Comment by ElleKayEm** [comment] 2020-10-19 12:50
@yiyi0724 
This is a community garden.  If you want tomatoes, you're welcome to start digging.  In the meantime, DeDRM 6.8 works just fine on calibre 4.23.

**Comment by 1031982** [comment] 2020-10-19 16:10
Just out of curiosity, why is this not closed and a post pinned to state that DeDRM tools currently does not work on Calibre 5 and up, and that it's currently being worked on?
I upgraded not knowing this, but searching didn't show anything. When I came here to post the issue, I saw this and other posts saying the same info.
Wouldn't a pinned and locked topic help stop these posts?

**Comment by ElleKayEm** [comment] 2020-10-19 17:44
Not a bad idea.  I wonder if @apprenticeharper is aware of the option to pin issues.

**Comment by tartley** [comment] 2020-10-20 16:44
FWIW the first line of this project's README does say this. Plus, there are already about fifty issues filed describing the identical problem. People should search the existing issues before filing a new one (they might find useful info, like a workaround) but clearly our audience isn't generally familiar with that, so we need to do whatever we can to help document the situation.

I agree that a pinned forum topic might help.

**Comment by ElleKayEm** [comment] 2020-10-20 19:41
Not sure what would be the best issue to consolidate on, but there are two variations of "can't install DeDRM".  The most common lately being like the OP here where they are trying to install DeDRM 6.8 in calibre 5.x.  The other has been around forever where someone tries to install the whole archive instead of unzipping it and loading the plugin file.

**Comment by francwalter** [comment] 2020-10-20 20:28
Thanks just downgraded to 4.23 and it works again.

**Comment by tartley** [comment] 2020-10-21 17:01
Closing this as a dupe of https://github.com/apprenticeharper/DeDRM_tools/issues/1245, as suggested by @mu22le

**Closed by tartley** 2020-10-21 17:01 UTC
Labels: install-fail, python3-syntax

**Comment by tartley** [comment] 2020-10-22 20:28
Duplicate of #1245
