### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by LeducH** [apprenticeharper/DeDRM_tools#1298] opened 2020-10-09 10:39 UTC
I want to install the plugin calibre but I get the following error message 

```
calibre, version 5.2.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.2  embedded-python: False is64bit: True
Linux-5.8.14-arch1-1-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.8.14-arch1-1', '#1 SMP PREEMPT Wed, 07 Oct 2020 23:59:46 +0000')
Python 3.8.6
Interface language: None
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 317, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 282, in load
    m = importlib.import_module(plugin_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 174, in exec_module
    compiled = self.get_code()
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 170, in get_code
    return compile(self.get_source_as_bytes(fullname), f'calibre_plugins.{self.plugin_name}.{self.fullname_in_plugin}',
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax
```

**Comment by mendhak** [comment] 2020-10-09 15:43
This plugin isn't compatible with Calibre 5, see this issue: https://github.com/apprenticeharper/DeDRM_tools/issues/1298

You'll need an older (4.x) version of Calibre to use this plugin.

**Comment by tartley** [comment] 2020-10-20 21:06
Closing as dupe of https://github.com/apprenticeharper/DeDRM_tools/issues/1324

**Closed by tartley** 2020-10-20 21:06 UTC
