### ISSUE TITLE
Can't convert - error with Drm & Adobe Editions

### ISSUE THREAD

**Issue by Tarz-an** [apprenticeharper/DeDRM_tools#1313] opened 2020-10-14 03:43 UTC
I added the book from Adobe Digital Editions 4.5 

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 703, in initialize_plugins
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 282, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 174, in exec_module
  File "calibre\customize\zipplugin.py", line 170, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 703, in initialize_plugins
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 282, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 181, in exec_module
  File "calibre_plugins.goodreads.__init__", line 11, in <module>
ImportError: cannot import name 'quote' from 'urllib' (C:\Program Files (x86)\Calibre2\app\bin\python-lib.bypy.frozen\urllib\__init__.pyc)
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 703, in initialize_plugins
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 282, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 181, in exec_module
  File "calibre_plugins.dummy1.__init__", line 9, in <module>
ModuleNotFoundError: No module named 'urlparse'
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 703, in initialize_plugins
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 282, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 174, in exec_module
  File "calibre\customize\zipplugin.py", line 170, in get_code
  File "calibre_plugins.MondoUrania.__init__", line 41
    supports_gzip_transfer_encoding = True
                                         ^
TabError: inconsistent use of tabs and spaces in indentation
Traceback (most recent call last):
  File "calibre\gui2\ui.py", line 157, in __init__
  File "calibre\gui2\ui.py", line 171, in init_iaction
  File "calibre\customize\__init__.py", line 614, in load_actual_plugin
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 181, in exec_module
  File "calibre_plugins.obok_dedrm.action", line 24, in <module>
  File "calibre\customize\zipplugin.py", line 181, in exec_module
  File "calibre_plugins.obok_dedrm.dialogs", line 30, in <module>
  File "calibre\customize\zipplugin.py", line 181, in exec_module
  File "calibre_plugins.obok_dedrm.utilities", line 10, in <module>
ModuleNotFoundError: No module named 'StringIO'
FFF: INFO: 2020-10-14 11:40:44,065: calibre_plugins.fanficfare_plugin.prefs(215): Attempting to read settings from predecessor--FFDL
FFF: INFO: 2020-10-14 11:40:44,065: calibre_plugins.fanficfare_plugin.prefs(220): Using default settings
FFF: DEBUG: 2020-10-14 11:40:44,067: calibre_plugins.fanficfare_plugin.fff_plugin(210): Plugin FanFicFare macmenuhack file_path:C:\Users\Roanta\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
calibre Debug log
calibre 5.2  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: None
Failed to initialize plugin: 'C:\\Users\\Roanta\\AppData\\Roaming\\calibre\\plugins\\DeDRM.zip'
Failed to initialize plugin: 'C:\\Users\\Roanta\\AppData\\Roaming\\calibre\\plugins\\Goodreads.zip'
Failed to initialize plugin: 'C:\\Users\\Roanta\\AppData\\Roaming\\calibre\\plugins\\Kindle hi-res covers.zip'
Failed to initialize plugin: 'C:\\Users\\Roanta\\AppData\\Roaming\\calibre\\plugins\\MondoUrania.zip'
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && Package KFX (from KFX Input) (1, 34, 0) && CalibreSpy (1, 0, 82) && Count Pages (1, 10, 0) && FanFicFare (3, 23, 0) && Find Duplicates (1, 7, 2) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Set KFX metadata (from KFX Output) (1, 44, 0) && KFX Output (1, 44, 0) && Kindle Collections (1, 7, 29) && KindleUnpack - The Plugin (0, 82, 3) && Obok DeDRM (6, 7, 0)
calibre 5.2  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && Package KFX (from KFX Input) (1, 34, 0) && CalibreSpy (1, 0, 82) && Count Pages (1, 10, 0) && FanFicFare (3, 23, 0) && Find Duplicates (1, 7, 2) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Set KFX metadata (from KFX Output) (1, 44, 0) && KFX Output (1, 44, 0) && Kindle Collections (1, 7, 29) && KindleUnpack - The Plugin (0, 82, 3) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 80.21052631578947 x 79.51304347826087
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.47] splash screen shown
[0.47] Initializing db...
[0.70] db initialized
[0.70] Constructing main UI...
CalibreSpy: initialization_complete
[2.27] main UI initialized...
[2.27] Hiding splash screen
Starting QuickView
Failed to initialize plugin: 'C:\\Users\\Roanta\\AppData\\Roaming\\calibre\\plugins\\DeDRM.zip'
Failed to initialize plugin: 'C:\\Users\\Roanta\\AppData\\Roaming\\calibre\\plugins\\Goodreads.zip'
Failed to initialize plugin: 'C:\\Users\\Roanta\\AppData\\Roaming\\calibre\\plugins\\Kindle hi-res covers.zip'
Failed to initialize plugin: 'C:\\Users\\Roanta\\AppData\\Roaming\\calibre\\plugins\\MondoUrania.zip'
[8.27] splash screen hidden
[8.27] Started up in 8.27 seconds with 4773 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xa4\xe5\xbd\x16\xe7\x0c\x8a&\xbf\xcf\xcc\xbc\xc1\xf3j\xcf\xa4\xba\xca\xf1\xeb@ |[\x05\x8cl1*,\xe8', b'C:\\Users\\Roanta\\Documents\\My Digital Editions\\The Lioness Wakes.epub']
Added The Lioness Wakes to db in: 0.0
Added 1 books in 0.4 seconds

**Comment by tartley** [comment] 2020-10-20 20:47
I think you're trying to use DeDRM in a recent (5.x) version of Calibre, is that correct? Current releases of DeDRM only work in older version of Calibre (4.x), you will have to downgrade.

Closing this issue as a dupe of https://github.com/apprenticeharper/DeDRM_tools/issues/1324

**Closed by tartley** 2020-10-20 20:47 UTC
Labels: duplicate, install-fail, python3-syntax
