### ISSUE TITLE
Support kindle kfx format

### ISSUE THREAD

**Issue by extesy** [apprenticeharper/DeDRM_tools#38] opened 2015-09-16 02:47 UTC
Is there any chance to support decrypting new kfx format? http://the-digital-reader.com/2015/08/11/kindle-ebooks-with-improved-typography-use-new-kfx-file-format/

**Comment by apprenticeharper** [comment] 2015-09-16 06:42
It would be great to support the new format. And the new azw3/azw6 combo files too. But reverse engineering a new DRM scheme and format is a hard task, especially one that's only on physical kindles.

If anyone comes up with a method, I'll add it to the tools as soon as possible.

**Comment by extesy** [comment] 2015-09-17 23:23
According to http://www.mobileread.com/forums/showthread.php?t=263902 it appears that DRM scheme in kfx format is not device-dependent. It's possible to simply move the files between different Kindle devices (even without associated Amazon account) and it still works. So basically it's just a reversible encryption with all required for decryption data stored in those files.

**Comment by mbrown3** [comment] 2015-09-24 19:00
Would LOVE for this to happen.

**Comment by angelnana** [comment] 2015-10-26 07:08
Decrypting new kfx format is possible, of course. 

But firstly you need to sync your books via Kindle for PC/Mac, this sync will make these books downloaded as AZW format, then remove drm from AZW please.

As what I known, there is no good solution to decrypte azw6 format books.

http://www.epubor.com/how-to-converter-kfx-books-to-epub-azw3-mobi-pdf.html

**Comment by ElleKayEm** [comment] 2015-10-26 17:44
angelana,

For AZW6, if you have an e-ink kindle, then you can download an AZW3 for it from the website and then decrypt that.

**Comment by angelnana** [comment] 2015-10-27 01:25
@ElleKayEm 

Thank you so much, this solution helped me.

**Comment by gitasong** [comment] 2016-09-26 06:16
Amazon is not allowing me to download the AZW3 for a book I've purchased in AZW6 format. It keeps giving me the following error message: 

"You have selected content that is not compatible with any of your registered devices. Please remove incompatible content from selection for eligible devices to appear."

My registered devices include Kindle for Mac, an old Kindle Paperwhite (1st generation, I think), and Kindle for Android.

**Comment by jessehouwing** [comment] 2016-09-26 06:41
Azw6 is a special format for graphic novels, comics and magazines and is
only available on specific devices. Since the graphic content is stored
'outside' of the book file, it can't be saved as an awz3 file. The file
would simply become too large.

**Comment by gitasong** [comment] 2016-09-26 16:57
That's not the case for this book. This book simply uses a nice font with the AZW6 "advanced typesetting" feature. There's zero reason why it couldn't be offered in AZW3. This is a case of Amazon wanting to control distribution and/or make an extra buck by forcing you to upgrade their products.

**Comment by ElleKayEm** [comment] 2016-09-27 00:31
I'm happy to discover that all my comics (AZW6 when downloaded directly to my Paperwhite) will now download to Kindle for PC as AZW3.  No need to "download & transfer via USB" for my Paperwhite anymore.  On the product pages they say they're also available for Kindle for Mac.  Is that not the case for your book, gitasong?

**Comment by gitasong** [comment] 2016-09-27 00:46
It may be, but my machine is too old; Kindle for Mac is no longer supported (and the old versions no longer work, believe it or not).

**Comment by ElleKayEm** [comment] 2016-09-27 01:02
The 1st generation Paperwhite is also listed.  (They call it 5th gen.)  Even Kindle Keyboard.  Are you sure that Paperwhite is still registered to that account?

**Comment by gitasong** [comment] 2016-09-27 01:41
Maybe it's 2nd generation; I'm not sure. And yes—it's still registered. I was on the phone with Amazon Kindle support for like 45 minutes today. The issue seems to be that the publisher hasn't issued this book in AZW3 format yet. They're giving me a refund. Anyway, it would really nice to figure out how to circumvent this issue.

**Comment by ElleKayEm** [comment] 2016-09-27 02:06
That sounds pretty flimsy to me!  Blame the publisher!  But at least they're good about refunds.  I usually get comics from Google.  They're often available in both epub and pdf (one purchase) and can be DeDRMed.

**Comment by apprenticeharper** [comment] 2017-01-06 06:51
Now that KFX is being downloaded by Kindle for PC 1.19, I hope that some developers will work on reverse engineering it. I'd love to hear from anyone doing this.

**Comment by j-howell** [comment] 2017-01-06 12:22
In the mean time I have a suggestion. The latest version of K4PC uses the same extension, .azw, for all book formats..Encrypted KFX containers begin with an 8 byte signature that includes the string "DRMION". An explicit error message for this case would avoid some confusion in diagnosing DRM removal problems.

**Comment by apprenticeharper** [comment] 2017-01-09 07:13
That's a good idea. It might be worth doing another version of the tools just to cut down on questions at the blog. And there is an Obok update that should be released in a full version. Hmm...

**Comment by sporks5000** [comment] 2017-02-08 11:23
Is there anyone that donations could be made to in order to increase the likelihood of this occuring?

**Comment by apprenticeharper** [comment] 2017-02-09 06:55
I don't accept donations for these tools. I hope that someone is working on KFX decryption/decoding, but I don't know of anyone at the moment.

**Comment by tmthywynn8** [comment] 2017-03-03 21:38
I notice that these KFx formats include a separate file with a .md extension. Is there a possibility that they are just encrypted markdown files? If so, is there a possibility of just decrypting the .md files? I understand this is a separate issue from the KFX one, but it's worth a shot to ask.

**Comment by j-howell** [comment] 2017-03-03 21:51
In this case "md" is short for metadata. It holds information about the book, such as author and title. This file is not encrypted, but it is in KFX binary container format, making it difficult to interpret.

**Comment by angelnana** [comment] 2017-03-21 03:01
Hello,

Thanks for your sweet suggestion, and in fact our developer now is dealing
with this issue, we will consider your idea and will find out the solution
soon.

But until now if you want to decrypt your KFX Kindle files, I still
recommend you use Kindle for PC/Mac reading app to sync your Kindle books,
then use Epubor Ultimate.

Thank you very much.



2017-03-04 5:52 GMT+08:00 John Howell <notifications@github.com>:

**Comment by apprenticeharper** [comment] 2017-03-23 06:33
Note that Epubor Ultmate does not remove DRM from KFX format files. This is unsurprising, since it's built on the scripts released here.

**Comment by ElleKayEm** [comment] 2017-03-31 13:40
Don't waste your money on Epubor.  It's simply a repackaging of the tools freely provided here.

**Comment by j-howell** [comment] 2017-04-25 12:13
For those interested in the workings of KFX, Amazon has documentation for Ion, the data format that KFX is based on, online at https://amznlabs.github.io/ion-docs/

Reference implementations of Ion in Java, C and Python can be found at https://github.com/amznlabs

**Comment by apprenticeharper** [comment] 2017-07-10 05:54
Thanks for lulzkabulz, the KFX encryption from Kindle for PC has now been reverse engineered. The code given is in Pascal, not Python, and removes the decryption only, leaving a document in the Ion format (see j-howell's comment above.)

However, the conversion of the decryption to python is essentially mechanical, and conversion from Ion to other formats will probably be relatively straight-forward.

I'll be having a go at the Pascal->Python conversion myself, but I don't have much free time to spend on it. Contributions to this, or the Ion -> ePub conversion task are very welcome.

**Comment by apprenticenaomi** [comment] 2017-07-13 07:26
Hi,

I [had a go at the mechanical Pascal to Python conversion](https://gist.github.com/apprenticenaomi/b0103db2ac134cb51a3ead92f1d99f3a) myself.  I've tested it with a KFX ebook and can successfully decrypt it (see main.py `decrypt()`).  The various other print / debugging methods seem to work ok too.

Conversion from the output to EPUB may be more difficult, but it looks like Calibre already has some support there.

Thanks lulzkabulz for the original work.

**Comment by jcsalomon** [comment] 2017-07-13 20:45
@apprenticenaomi, what does a decrypted e-book in Ion format look like?

**Comment by apprenticenaomi** [comment] 2017-07-13 22:04
@jcsalomon It's a CONT (container) file with a bunch of ENTYs (entities).  The book contents are embedded in there as uncompressed UTF-8.  I haven't looked at the structure too much.

You can "buy" a free book from Amazon, download it, and try it out yourself.  Nothing in the file looks personally identifying, but I'm not about to upload a DRM-stripped book :-).

**Comment by apprenticeharper** [comment] 2017-07-14 05:42
Many thanks for the python conversion! If anyone fancies having a go at convertingwhat I'm assuming is an ION format book (see the comment by j-howell), I suggest that conversion to epub (version 2) might make most sense and be easiest.

**Comment by jcsalomon** [comment] 2017-07-14 13:33
Everyone involved in this thread probably already has seen something like this, but for the benefit of folks reading this later: @j-howell has uploaded a snippet of a KFX file (from Kindle Previewer) unpacked to Ion at <https://mobileread.com/forums/showthread.php?t=288540#post3552191>.

**Comment by j-howell** [comment] 2017-07-14 13:52
Terminology: A KFX book is split over multiple files each using KFX container format. A KFX container is conceptually similar to the PDB format used as the basis of MOBI and KF8. It holds a list of data records known as fragments or entities. The entities are data structures encoded in Amazon's Ion binary format. Amazon has an equivalent Ion text format, a superset of JSON, which can encode the same data in a human-readable fashion.

The process of converting a book from EPUB to KFX is handled by a very large Java program (KFXGenApp). It works much like a compiler, transforming the original EPUB into rendering instructions. In the process any information in the original EPUB that is not relevant to how the book is rendered into pages is discarded. The result bears little resemblance to the HTML/CSS within an EPUB. This is far different from KF8, which is just the original EPUB content packed into a MOBI container.

I believe that it will take a large effort to develop software that can convert KFX back into EPUB. (And even if successful the result will be inferior to that which can be obtained by just unpacking a KF8.) I propose that this effort is better left to an outside project, such as calibre, which is not hampered by the potential legal issues that come from being part of DRM removal software.

**Comment by apprenticenaomi** [comment] 2017-07-14 15:45
The converted Pascal program can parse and unpack the KFX container format, but it doesn't do much beyond that.  Amazon's Python reference implementation might be the best way forward.

It does seem most reasonable for Calibre to do conversion, and leave DRM to this project.

**Comment by j-howell** [comment] 2017-07-14 16:12
I have looked at the Pascal program that was posted and it has multiple functions that do different things. This may be causing confusion.

One function implements the extraction of encryption keys from Kindle for PC. It duplicates existing functionality of the DRM tools.

Another function takes an encrypted KFX file (DRMION) and the extracted keys and removes the encryption, resulting in an unencrypted KFX container. That leaves a working KFX book without DRM. That function would be nice to have in the DRM removal toolkit.

A separate function decodes the KFX container format and the data records it contains in Ion binary format and outputs a human readable version of the data. That is useful for delving into the workings of KFX and could provide a starting point for conversion of KFX to EPUB.

**Comment by aph3rson** [comment] 2017-07-25 03:14
Just a quick note - if a user like myself stumbles upon this thread, and is looking for a "fix" here, it's possible to use an old version of the K4PC program. I use 1.17 (44170), available from [here](https://s3.amazonaws.com/kindleforpc/44170/KindleForPC-installer-1.17.44170.exe). This generates the specific AZW needed.

**Comment by lizzard** [comment] 2017-08-05 23:36
aph3rson, do you have a link to the Kindle 1.17 Mac version download page? Thanks.

**Comment by ElleKayEm** [comment] 2017-08-05 23:48
Kindle for Mac 1.17:
https://s3.amazonaws.com/kindleformac/44182/KindleForMac-44182.dmg

(Mentioned [here](https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac) in the FAQs.)

**Comment by j-howell** [comment] 2017-08-18 12:08
Someone asked on Apprentice Alf’s Blog about removing DRM from KFX books that were obtained via Kindle Unlimited and the response was that the DRM removal Tools are only intended for use on purchased books.

KFX voucher files have a license_type field that indicates whether that particular book is a rental, loan or purchase. I suggest that this field be checked if/when KFX DRM removal becomes part of the Tools.

**Comment by apprenticeharper** [comment] 2017-09-01 05:36
A very good suggestion. Thanks.

**Comment by j-howell** [comment] 2017-10-19 13:48
Two bits of KFX news:

1. I have released a calibre plugin that can convert from KFX to other formats. At present it is difficult to use due to the lack of KFX DRM removal support in a calibre plugin.

2. EPUBOR has announced that they now support DRM removal of KFX format. I assume that they incorporated the code that was posted here, but never integrated in the DRM TOOLS. It is probably only a matter of time before they add a KFX conversion function too.  :(

**Comment by apprenticeharper** [comment] 2017-10-20 07:46
Thank you again for all you work on this. My development time is limited at the moment, but I would welcome pull requests incorporating the new KFX decryption capability into the tools.

**Comment by j-howell** [comment] 2017-10-27 14:31
The download links for Kindle for PC/Mac 1.17 from Amazon listed under "A Recent Change to Kindle for PC/Kindle for Mac" in the FAQ are no longer operational.

**Comment by jostyee** [comment] 2017-12-15 08:21
@j-howell dmg backup: https://d.pr/f/94aJrl

**Comment by j-howell** [comment] 2017-12-15 13:30
I don't need the file myself, but others may find it useful.

I did a write-up that describes ways to work around KFX. It includes checksums to verify that you have found the correct older Kindle for PC or Mac file. (The one above looks good, for now.)

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by vdcbb** [comment] 2017-12-21 17:03
Is this the place to watch for when KFX decryption capability becomes available?

**Comment by ElleKayEm** [comment] 2017-12-21 17:10
This GitHub is the place to watch for when it gets integrated into the tools (and any other updates).

**Comment by bombcheck** [comment] 2017-12-21 20:28
While waiting for this to happen, using the old K4PC-App to get an AZW-Version of the book should do the trick...

**Comment by garfieldthecat** [comment] 2018-01-18 10:03
> EPUBOR has announced that they now support DRM removal of KFX format.

That's right. I have tried it: conversion and decryption work, but the final output is a text file that loses all the formatting, chapters, etc. I have contacted them to understand if there is a way around it.

**Comment by angelnana** [comment] 2018-03-07 00:58
This is because what you used is trial version, which only supports
converting books to text and only 20% contents.

2018-01-18 18:03 GMT+08:00 garfieldthecat <notifications@github.com>:

**Comment by apprenticeharper** [comment] 2018-03-10 18:20
Apologies that I have had no time to work on this yet. Pull requests welcome.

**Comment by ElleKayEm** [comment] 2018-03-29 00:37
@chorichori 

Start your own issue.  You shouldn't have any trouble using DeDRM with an AZW3 file.

**Comment by cemeyer** [comment] 2018-03-29 00:41
Re j-howell, the alluded to PR is #458 .  Let us know how it goes!

**Comment by j-howell** [comment] 2018-03-30 14:43
@voltagex has combined the pull request into a plugin zip file that can be used for testing. (See the comments of #458.)

The KFX Input plugin for calibre also needs to be installed to allow creation of a KFX-ZIP archive when a single KFX file is selected for import into calibre and to allow conversion to more useful formats.

I gave it a try on an assortment of KFX books from both Kindle for PC 1.21 and a Kindle running 5.9.4 firmware. I had to select books using the "Add books from a single directory" option in calibre, since calibre would not allow import of books KFX format from the Device view.

All but a few were able to have their DRM removed successfully! I will try those that didn't work in debug mode and see if I can find what is going wrong with them.

While testing I found a problem in the KFX Input plugin with the handling of e-book samples. I will work on a fix for that.

**Comment by cemeyer** [comment] 2018-03-30 15:27
@j-howell For the few that were unsuccessful, perhaps their `license_type != "Purchase"` (DeDRM_plugin/kfxdedrm.py)?  That could be expanded (or dropped).  (I don't know what possible values that string can have.)

**Comment by j-howell** [comment] 2018-03-30 21:19
> For the few that were unsuccessful, perhaps their license_type != "Purchase"

You were right, @cemeyer. It failed for books from Kindle Unlimited:

`DeDRM v6.5.5: Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.`

And for library books borrowed through OverDrive:

`DeDRM v6.5.5: Failed to decrypt with error: This book is licensed as PublicLibraryLending. These tools are intended for use on purchased books.`

I suppose @apprenticeharper will have to decide whether or not to keep that limitation when integrating the changes.

It also doesn't work for free Indic dictionaries in KFX format. Those use a different variant of KFX:

`The .kfx-zip archive does not contain an encrypted DRMION file`

It *did* work properly for all of the purchased books I tried.

**Comment by toXel** [comment] 2018-03-30 23:33
Isn't this protection intended behavior? Why should it be changed for KFX files?

**Comment by mafrosis** [comment] 2018-03-30 23:35
I've been testing the `KFX` branch written by @tomthumb1997. I see the following error with all the books sync'd down through the latest Kindle for Mac:

    The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

The [code which produces that message](https://github.com/tomthumb1997/DeDRM_tools/commit/75cad4080478b10e6d4339de3a7c069e70e30450#diff-545872edd077e5819ca01ea2cb4b7d66R203) checks the first 8 bytes of file for the special chars "DRMION". I checked all my `azw` files and they all have this same first 8 bytes!

    head -c 8 <azw_file>

Does anyone know more about how these tools work?

**Comment by j-howell** [comment] 2018-03-30 23:52
> Isn't this protection intended behavior? Why should it be changed for KFX files?

The explicit license type used in KFX format means that the check for purchased books will be more reliably enforced than for other Kindle formats. Personally, I think that is a good thing. Others may not agree.

**Comment by cemeyer** [comment] 2018-03-31 00:10
@mafrosis I think vouchers can be stored separately from kfx files by the Kindle software, but @
tomthumb1997 's plugin only handles kfx-zip with embedded voucher files.  See https://gist.github.com/apprenticenaomi/b0103db2ac134cb51a3ead92f1d99f3a#file-main-py-L30 for example (it seems to use a weird callback scheme to locate appropriately named ".voucher" files in the same directory as the book files).  Don't know when or how Kindle software decides to store zips or separate files.

**Comment by mafrosis** [comment] 2018-03-31 00:35
@cemeyer Thanks for the info. Very useful

@j-howell I don't use Calibre, but again very useful info.

**Comment by cemeyer** [comment] 2018-03-31 01:46
@j-howell Oh, KFX-zip is entirely something of your creation, not an Amazon thing?  I definitely think we should support vanilla kfx files from Amazon.  We can do both. :-)

> The explicit license type used in KFX format means that the check for purchased books will be more reliably enforced than for other Kindle formats. Personally, I think that is a good thing. Others may not agree.

Seems harmless, but you know crapware like EPUBOR is going to remove the check.

**Comment by j-howell** [comment] 2018-03-31 03:09
> Oh, KFX-zip is entirely something of your creation, not an Amazon thing?

It was decided that since books in KFX format are spilt into multiple files and calibre handles all books a single files that combining the KFX files that make up a book into a zip archive was the best way of making it work within that restriction of calibre.

**Comment by apprenticeharper** [comment] 2018-04-05 17:32
Thanks, everyone for all your work on this. I've merged the pull request, tweaked some readmes and version numbers, and v6.6.0 has now been released. It needs testing and no doubt some bug fixes. And the FAQs could do with an update. But that's all I have time to do today. Anything else will have to wait until I have some more free time.

**Comment by wallyreport** [comment] 2020-10-30 19:15
I am using Devaun, and having the same problem.

> Linux myserver 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

I cannot seem to upgrade calibre beyond 3.9.1. 

I have python 2.7 installed.

**Comment by angelnana** [comment] 2020-11-02 07:42
Contact Calibre official for help please.

**Comment by ElleKayEm** [comment] 2020-11-02 13:15
@wallyreport 
I'd ask about calibre issues over in the calibre forum at MobileRead.

**Closed** 2020-11-27 19:55 UTC
