### ISSUE TITLE
Problem with plugin DRM remover and calibre 5.0.1

### ISSUE THREAD

**Issue by christianbeugnier199** [apprenticeharper/DeDRM_tools#1271] opened 2020-10-01 10:18 UTC
When I try to load the plugin trought Calibre I revceive the following error
![calibre](https://user-images.githubusercontent.com/72193003/94797263-2ef07400-03e0-11eb-8607-968b8648cb54.PNG)

**Comment by ElleKayEm** [comment] 2020-10-01 10:34
DeDRM is not compatible with calibre 5 yet.  Use calibre 4.23.  Also, the file you're trying to load in that screenshot is an older DeDRM version and it's the whole archive, not the plugin.  Current release is 6.8.0.  Unzip DeDRM_tools_6.8.0.zip and load DeDRM_Plugin.zip.

**Comment by christianbeugnier199** [comment] 2020-10-01 13:19
Now, it's ok. You can close the ticket

**Comment by ElleKayEm** [comment] 2020-10-01 14:52
As the person who opened it, you can close it.  I'm unable to.

**Comment by fdicarlo** [comment] 2020-10-01 15:41
I am suggesting to merge with #1264 as the same topic and solution

**Comment by hamkg** [comment] 2020-10-01 18:36
See https://github.com/apprenticeharper/DeDRM_tools/issues/979#issuecomment-700960177
This solution seems to work at least for kindle and epub, windows and linux.

**Comment by tartley** [comment] 2020-10-20 21:24
Closing this issue as a duplicate of https://github.com/apprenticeharper/DeDRM_tools/issues/1324. Shout if that's not right.

**Closed by tartley** 2020-10-20 21:24 UTC
