### ISSUE TITLE
Please help for ADE

### ISSUE THREAD

**Issue by gelinstar** [apprenticeharper/DeDRM_tools#1308] opened 2020-10-12 04:20 UTC
Book can only be opened using Adobe 4.5, used calibre 4.3 with the plug in for 6.8.  unable to remove DRM.

**Comment by tartley** [comment] 2020-10-20 20:58
Closing as dupe of https://github.com/apprenticeharper/DeDRM_tools/issues/1323

**Closed by tartley** 2020-10-20 20:58 UTC
Labels: duplicate

**Comment by ElleKayEm** [comment] 2020-10-20 21:18
@gelinstar 
Can you open it in ADE 2.0.1 authorized with the same Adobe ID?

**Comment by gelinstar** [comment] 2020-10-21 01:30
no, i can't
