### ISSUE TITLE
how to unlock DRM from kindle fire hd

### ISSUE THREAD

**Issue by binglingyu1939** [apprenticeharper/DeDRM_tools#1321] opened 2020-10-17 10:28 UTC
i have a kindle fire HD 
Type :Fire HD 10 (9th Generation)
i want to know ,i have add the Serial number in the eink kindle ebooks ,but it doesnt work.please help me 
by the way ,do you know how to unlock the rbdigital magazine,thank you

**Comment by ElleKayEm** [comment] 2020-10-19 17:50
DeDRM doesn't work on books from or for a Kindle Fire.  If you do not have an E-ink Kindle, then you can use Kindle for PC or Mac.

Not aware of anything for rbdigital.

**Comment by tartley** [comment] 2020-10-20 17:08
Closing this as a dupe of "Update and refine instructions for DeDRM use" https://github.com/apprenticeharper/DeDRM_tools/issues/1328 (in particular, that it does not work for Kindle Fire books.)

**Closed** 2020-10-20 17:08 UTC
Labels: docs, duplicate
