### ISSUE TITLE
Can't DeDRM KFX-ZIP with v. 6.6.0

### ISSUE THREAD

**Issue by aTomicTurnip** [apprenticeharper/DeDRM_tools#503] opened 2018-05-08 15:56 UTC
With **Kindle for pc v 1.23.1** ebooks borrowed from **Kindle unlimited** are saved in **KFX-ZIP** format, once imported in Calibre. With Kindle v 1.17 they were saved in azw3 or mobi.
Is anything you can do about? 

- **DeDRM v 6.6.0**

**Comment by ElleKayEm** [comment] 2018-05-08 16:29
I believe the tools intentionally do not remove DRM from Kindle Unlimited KFX format books.

**Comment by cgm707** [comment] 2018-05-25 00:34
I have the plugin that is supposed to convert a .kfx-zip file, but how do I get it to do that? I don't see an option like that when I highlight the book that I want to open, and convert. Is there another means to open this file?

**Comment by j-howell** [comment] 2018-05-25 02:30
> I have the plugin that is supposed to convert a .kfx-zip file, but how do I get it to do that?

To convert between different formats in calibre select the book entry and then choose Convert Books from the toolbar. If you need more help with conversion ask in the calibre forum on MobileRead.

**Comment by ElleKayEm** [comment] 2018-05-25 09:16
@cgm707

If you're having trouble with DRM removal (and it's not a borrowed or rented book), start your own issue.

**Comment by GuardianMajor** [comment] 2018-05-25 18:52
If I may interject, I have the latest DeDRM plugin, the latest KFX from @j-howell and the book is not borrowed or unlimited, it is a straight purchased book and while importing it to Calibre will properly convert it to KFX-Zip file (I even tried importing it as a KFX-Zip file) shows the cover and the meta information, when you try to read it, it states that it can't since it has DRM, am I missing something or doing something incorrectly?

BTW, be happy to provide the book for your testing if you wish, just let me know where and how you want it and I will happily share it for debugging purposes. I can give you the uncompressed folder and/or also the KFX-Zipped file. Thanks in advance.

**Comment by j-howell** [comment] 2018-05-25 19:15
>  ... Calibre will properly convert it to KFX-Zip file (I even tried importing it as a KFX-Zip file) shows the cover and the meta information, when you try to read it, it states that it can't since it has DRM, am I missing something or doing something incorrectly?

If a KFX import is successful and DRM is removed you will see KFX format in calibre. If DRM removal fails the imported book will show as KFX-ZIP format because the component files that make up the book cannot be combined into a single KFX file if DRM is present. In either case the book's metadata will be readable since that is not protected by DRM.

I suggest that you post an import log to see what is going wrong.

**Comment by ElleKayEm** [comment] 2018-05-25 19:40
@aTomicTurnip
You can close this issue.  That's a feature, not a bug.

@GuardianMajor 
Please start your own issue.

**Comment by GuardianMajor** [comment] 2018-05-25 20:22
@j-howell I see, thank you for that. Now this might sound like the dumbest question ever, but can you tell me how I would get that import log to share? Would that be the same as restarting Calibre in "debug mode"? Or is it somewhere else or some other way, I am sorry to ask, I haven't had an opportunity to need that in the past, so a learning moment.

@ElleKayEm I am sorry but I felt it was relevant to this issue especially your response to the previous user stating that "and it's not a borrowed or rented book" and it wasn't my case, so I felt that meant it was ok to say it here. Is there such a huge issue to put it here?

**Comment by j-howell** [comment] 2018-05-25 21:04
> WAS originally "purchased" while I had unlimited active on the account, will that somehow make a difference?

The DRM voucher indicates the licence type that was in effect when the book was downloaded. If you borrowed the book through KU and then subsequently paid for it you may need to delete the book from your system and re-download it in order to update the license file.

**Comment by j-howell** [comment] 2018-05-25 22:28
Those questions are answered in the FAQ:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cant-get-the-tools-to-work-on-my-rented-or-library-ebooks

**Comment by GuardianMajor** [comment] 2018-05-25 23:39
@j-howell Thank you, didn't realize they were there, my bad. So it is debug mode, thanks. Will get that right away.

I understand owning it, makes sense. But how is unlimited not owning it? Thanks again.

**Comment by ElleKayEm** [comment] 2018-05-26 00:06
@GuardianMajor 
Not a big deal to continue in this thread since the first two haven't come back.  But only the OP (or Apprentice Harper) can close it.  So it's generally more organized/less confusing to have separate issue for each person's questions.

With Kindle Unlimited you're not buying books -- you're renting/borrowing.  You can only have so many at a time, and you don't get to keep books if you cancel.  You're just paying Amazon for their book subscription service.  Authors get paid based on how much you read on your Kindle device/app.  Remove the DRM and authors get nothing.

**Comment by GuardianMajor** [comment] 2018-05-26 00:17
@ElleKayEm I completely understand. I am going to provide the log as was requested and if it ends up going somewhere further, I promise to start a new issue, refer to this and continue from there. Apologies.

Really? Unlimited is renting/borrowing? I have had books that were on my account during unlimited and long after my unlimited was over, they still have remained on my account and I have full access to them through the cloud reader (amazon's own system), the kindle devices and PC desktop reader. Why would they remain if you were renting them? Wouldn't they have removed it? Expired it? or something? Hmm.. I need to ask them about this. Because the books I get form the public library, they show up, you return them, they expire or if the load period ends it expires and it shows. I have at least 19 books from when I had unlimited and they are still there, fully accessible. In fact, I just had to reinstall the client on one of my PCs and when I authorized the device, it all came pouring on that too. Been actually reading two of them in the past week. So confusing. For all their awesomeness, I sometimes really hate ebooks because a real book, you either have it in your hand or you don't, no one decides if you own it or not, when or how.

@j-howell In the meantime, [here is the log](https://gist.github.com/GuardianMajor/feba030bb6bb93f11bdad802bc31b06d) you asked for, it is generated importing from the KFX-ZIP file since on the forum it seemed to be your preferred method. But if you like I can also do it directly from the folder, if you think that would yield something different. Thanks again.

**Comment by ElleKayEm** [comment] 2018-05-26 00:47
That's very different from my own experience with Kindle Unlimited.  I tried it out for a couple months.  After the tenth book, I had to return something to get another.  When I cancelled and that month ended, the books I hadn't already returned were removed from my account.  But even so, authors get paid based on the amount of the book you read, and Amazon can't know that if you remove DRM.  So that's why it isn't supported here.  (I want to know where to sign up for your truly unlimited plan! ;))

**Comment by j-howell** [comment] 2018-05-26 03:04
I agree with @ElleKayEm in being surprised and confused about how KU is working for you.

Looking at your log it seems that the DeDRM plugin was unable to find the key to decrypt the book. The file names in the log look like they might have come from the Kindle for Android app or a Fire tablet. If so see the FAQ:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#why-dont-the-tools-work-with-kindle-for-android-ebooks

**Comment by aTomicTurnip** [comment] 2018-05-26 06:58
@ElleKayEm I understand that it's not intended, but with the last version it worked.
I'm not sure if it was a bug not intended and now is fixed

**Comment by GuardianMajor** [comment] 2018-05-26 20:04
@ElleKayEm I don't know honestly, maybe a glitch on their system or because I am prime it is behaving different, don't know honestly. That's why I said, I need to ask them to find out. If they get back to me, I will share what they said in case it helps everyone. My unlimited is no more special than any other, every so often they offer like 3 months for $2 and I sign up but I don't keep it after that, since I get and read most of what I need form the library and it sufficient for my needs and what I like and want to keep, I just buy it. I wish I had more to share on why it is behaving differently for me 😞 

@j-howell Yeah I am beginning to think that there is something wrong too, but I will find out if/when they get back to me on the why and how of it. Maybe its a bug and they will fix it and I will lose them all, but that's ok with me as long as it is how it should be, but if I find otherwise, I will let you all know.

You would be correct, this particular book could only be read on Kindle Android for some reason they say that the "graphic" components are only compatible there, so I can either read it on Android client or their cloud reader (on the website) but not on the PC. I will take a look at what you linked, thank you for taking a look.

**Comment by ElleKayEm** [comment] 2018-05-26 20:42
Oh, maybe the books are also in Prime Reading.  I think all those books are in Kindle Unlimited too (but not all Kindle Unlimited are in Prime).  You may get to "check out" more of those at a time too.

Yeah, unfortunately if you can't download to Kindle for PC/Mac or an E-ink Kindle, then you can't remove the DRM.

**Comment by GuardianMajor** [comment] 2018-05-27 02:35
@ElleKayEm Your guess is as good (probably better) than anything I can think of, so by all means quite possible. Hopefully they will get back to my request for explanation with something that will clarify it for sure. I will happily update to share it once I know something.

Thank you for that information, I appreciate both your and John's helps on this. I will check and see if their "newest" client for PC is now able to read it, then give that a shot then. Otherwise, I guess I have to resign myself to just reading this on the tablet and website. I was just hoping for an offline reading on a larger desktop screen, but such is how the cookie crumbled. Thank you again both.

**Comment by apprenticeharper** [comment] 2018-06-02 16:12
I think I can close this now. If anyone needs more clarification or help, please start a new issue.

**Closed by apprenticeharper** 2018-06-02 16:12 UTC
