### ISSUE TITLE
Invalid sintax error

### ISSUE THREAD

**Issue by Chrunchbang** [apprenticeharper/DeDRM_tools#1035] opened 2020-03-24 16:09 UTC
HI, I have installed Calibre 4.12 on linux Opensuse Tumbleweed and tried to install the DeDRM_tools_6.7.0.
I extracted the zip file and I was able to install Obok_plugin.zip. But I have an error for DeDRM_plugin.zip.
What can i do? If the error is known please send me the link to fix the problem. Thank you!

calibre, version 4.12.0
ERRORE: Eccezione non gestita: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 4.12  embedded-python: False is64bit: True
Linux-5.5.9-1-default-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.5.9-1-default', '#1 SMP Thu Mar 12 06:33:05 UTC 2020 (70a6377)')
Python 3.8.2
Interface language: it
Successfully initialized third party plugins: Obok DeDRM (6, 7, 0)
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/gui2/preferences/plugins.py", line 318, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 202, in load
    m = importlib.import_module(plugin_module)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 179, in load_module
    compiled = compile(code, 'calibre_plugins.%s.%s'%(plugin_name,
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment] 2020-03-24 18:47
See #986 and #928.

**Comment by Chrunchbang** [comment] 2020-03-24 20:13
I don't understand if the problem is that I have not installed the program from its site or it's that I should use python2

**Comment by vasyugan** [comment] 2020-03-31 06:19
> I don't understand if the problem is that I have not installed the program from its site or that I should use python2

One option is to install [the calibre flatpak](https://flathub.org/apps/details/com.calibre_ebook.calibre) which I guess still uses python 2.x. It seems to be maintained by the upstream developer himself.

**Comment by ElleKayEm** [comment] 2020-03-31 13:04
The regular non-beta release of calibre is still on Python 2 as well:

https://calibre-ebook.com/download_linux

**Comment by vasyugan** [comment] 2020-03-31 18:22
> The regular non-beta release of calibre is still on Python 2 as well:
> 
> https://calibre-ebook.com/download_linux

Sure, but some of the download options suggested there make me shudder:

`sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin install_dir=/opt`

That's executing a shell script as root right from the Internet. Not exactly good practice.

Really, the flatpak is the cleanest and safest option.

**Comment by tartley** [comment] 2020-10-21 03:02
Closing as a dupe of https://github.com/apprenticeharper/DeDRM_tools/issues/1324

**Closed by tartley** 2020-10-21 03:02 UTC
