### ISSUE TITLE
Error installing DeDRM_Plugin in Calibre 5.2 (64bit)

### ISSUE THREAD

**Issue by secannon** [apprenticeharper/DeDRM_tools#1302] opened 2020-10-10 00:24 UTC
When I attempt to install the DeDRM_Plugin.zip in Calibre 5.2, I receive the following error:

calibre, version 5.2.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && Package KFX (from KFX Input) (1, 34, 0) && Generate Cover (1, 5, 25) && Hyphenate This! (0, 1, 3) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Set KFX metadata (from KFX Output) (1, 44, 0) && KFX Output (1, 44, 0) && Overdrive Link (2, 42, 0) && Prettify Cover (1, 5, 0) && Resize Cover (1, 1, 0) && Obok DeDRM (6, 7, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 282, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 174, in exec_module
  File "calibre\customize\zipplugin.py", line 170, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by homiyogi** [comment] 2020-10-10 01:23
I'm getting the same error after install the DeDRM_Plugin.zip in Calibre 5.2.

calibre, version 5.2.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.2  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "calibre/customize/ui.py", line 472, in add_plugin
  File "calibre/customize/ui.py", line 61, in load_plugin
  File "calibre/customize/zipplugin.py", line 282, in load
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 174, in exec_module
  File "calibre/customize/zipplugin.py", line 170, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by tlahuizcalpantecutli** [comment] 2020-10-10 03:20
Same thing in MacOs Catalina 10.15.7 with Calibre 5.2:

calibre, version 5.2.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.2  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
...
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by tartley** [comment] 2020-10-10 04:49
Hey. There are about 50 issues already reported to this effect.

Calibre 5 requires Python3. The last release of this plugin is Python2. It is being updated to Python3, but there are a lot of non-trivial changes to be made.

**Comment by telljmc** [comment] 2020-10-10 05:03
is there an ETA or too early to comment?

**Comment by tartley** [comment] 2020-10-10 05:05
Hard to say. There's a bunch of people doing it, each working on whatever functionality interests them personally. I'm not very familiar with the project, but at a wild guess I'd say a small number of weeks.

**Comment by telljmc** [comment] 2020-10-10 05:18
I am comfortable with Python and have been doing some other conversions from 2 to 3 lately.  How do I get involved?

**Comment by teemue** [comment] 2020-10-10 10:25
Load the latest code from github, create a ZIP archive of the contents of DeDRM_plugin - folder and install plugin using this ZIP.

**Comment by tartley** [comment] 2020-10-10 12:34
Be aware there are several branches in progress already doing this. I have one that runs 2to3 on the whole DeDRM-plugin directory. I'm just trying to verify it actually works, but am having problems getting my kindle key. See the PR tab.

Some things that have me pause when I started yesterday.

**Comment by tartley** [comment] 2020-10-20 21:08
Closing as a dupe of https://github.com/apprenticeharper/DeDRM_tools/issues/1324

**Closed by tartley** 2020-10-20 21:08 UTC

**Comment by ElleKayEm** [comment] 2020-11-19 13:21
In answer to the first 3 posters to this thread, stick with calibre 4.23 for DeDRM 6.8.
