### ISSUE TITLE
DeDRM is not working

### ISSUE THREAD

**Issue by kai4711** [apprenticeharper/DeDRM_tools#311] opened 2017-07-12 10:09 UTC
Hello!
I have installed Kindle for PC 1.17 and imported all ebooks i have bought on amazon. I also have installed Calibre 3.3.0 with the DeDRM_plugin. But if i try to convert an imported azw-file, i get the message, that the ebook is still DRM-protected.

calibre Fehlerdiagnoseprotokoll
calibre 3.3  embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 5, 4)
calibre 3.3  embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 69.9684361549 x 69.9795918367
Using calibre Qt style: True
Starting up...
Started up in 6.98 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xefa\xbf8@\xd9^4\x8c\xd2\x07o\xae14\xc0nw\xaf\xcf\x91\xc0\x8b(\xa0\xf6\xb3\xba\xb5\x1f\xfc\xfd', 'C:\\Users\\P\xc3\xbcschel\\Documents\\My Kindle Content\\B00A2QD2Z2_EBOK.azw']
DeDRM v6.5.4: Trying to decrypt B00A2QD2Z2_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 256
Extra Data Flags: 1
Decrypting Kindle Format 8 ebook: Die Fleischmafia (German Edition)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Pschel\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Pschel\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1986904068' and UserName '50fc736368656c'
DeDRM v6.5.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 256
Extra Data Flags: 1
Decrypting Kindle Format 8 ebook: Die Fleischmafia (German Edition)
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds
C:\Program Files (x86)\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Die Fleischmafia (German Edition) to db in: 0.2
Added 1 books in 0.5 seconds
Worker Launch took: 0.134000062943
Job: 1 Buch 1 von 1 (Die Fleischmafia (German Edition)) konvertieren finished
Buch 1 von 1 (Die Fleischmafia (German Edition)) konvertieren
	C:\Program Files (x86)\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  pdf_sans_family: u'MS Shell Dlg 2'
	  cover: u'C:\\Users\\PSCHEL~1\\AppData\\Local\\Temp\\calibre___rp2d\\lelhyp.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\PSCHEL~1\\AppData\\Local\\Temp\\calibre___rp2d\\hkjem9.opf'
	  output_profile: 'kindle_fire'
	  verbose: 2
	Resolved conversion options
	calibre version: 3.3.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\PSCHEL~1\\AppData\\Local\\Temp\\calibre___rp2d\\lelhyp.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x04131EF0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.KindleFireOutput object at 0x01A6B2B0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Courier New',
	 'pdf_mono_font_size': 16,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'MS Shell Dlg 2',
	 'pdf_serif_family': u'Times New Roman',
	 'pdf_standard_font': u'serif',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\PSCHEL~1\\AppData\\Local\\Temp\\calibre___rp2d\\hkjem9.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\PSCHEL~1\AppData\Local\Temp\calibre___rp2d\yx1y1y.azw
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  Die Fleischmafia (German Edition) (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: Die Fleischmafia (German Edition)

stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['X\x92\x7f\x12c6\xe0\n\xcdo\x9a[\x8e\x18\xc2\xfb\xcd\x11\xab\xa5\xdb\x9d\xd0kj\xce\x13\xb5\x17g)\x91', 'C:\\Users\\P\xc3\xbcschel\\Documents\\My Kindle Content\\B00A2QD2Z2_EBOK.azw']
DeDRM v6.5.4: Trying to decrypt B00A2QD2Z2_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 256
Extra Data Flags: 1
Decrypting Kindle Format 8 ebook: Die Fleischmafia (German Edition)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Pschel\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Pschel\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1986904068' and UserName '50fc736368656c'
DeDRM v6.5.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 256
Extra Data Flags: 1
Decrypting Kindle Format 8 ebook: Die Fleischmafia (German Edition)
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.1 seconds
Added Die Fleischmafia (German Edition) to db in: 0.1
Added 1 books in 0.5 seconds

Can anyone help?

**Comment by kai4711** [comment] 2017-07-12 11:04
Ok... i've solved the problem... my username contains an "ü"...

Can be closed ;-)

**Comment by apprenticeharper** [comment] 2017-07-14 05:33
Please see this issue: https://github.com/apprenticeharper/DeDRM_tools/issues/118

Please download the new version of the plugin from here: https://github.com/apprenticeharper/DeDRM_tools/tree/master/DeDRM_calibre_plugin

and see if that fixes the problem with the non-ASCII character in your username. Thanks.

**Comment by apprenticeharper** [comment] 2018-01-20 16:37
Closing, as I think the problem is solved.

**Closed by apprenticeharper** 2018-01-20 16:37 UTC
