### ISSUE TITLE
[master][Calibre5] DeDrm failed to remove from Kindle book

### ISSUE THREAD

**Issue by odysseus654** [apprenticeharper/DeDRM_tools#1279] opened 2020-10-03 08:53 UTC
This was installed by downloading the current master branch, zipping up, and installing the plugin.

The book appeared to load successfully into the library but could not be converted.

(insert usual disclaimer work in progress not a release yes understood).  Hope this helps.

```
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing C:\Users\Heather\Documents\My Kindle Content\B00ZEQMP8U_EBOK\B00ZEQMP8U_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\Heather\AppData\Local\Temp\calibre_z38xszg1\ea3lwu49.kfx-zip
DeDRM v7.0.0: Trying to decrypt ea3lwu49.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.00.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
DeDRM v7.0.0: Failed to decrypt with error: Invalid file format
DeDRM v7.0.0: Looking for new default Kindle Key after 0.1 seconds
DeDRM v7.0.0: Exception when getting default Kindle Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 533, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 218, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 261, in __init__
calibre_plugins.dedrm.mobidedrm.DrmException: Invalid file format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 543, in KindleMobiDecrypt
  File "site-packages\calibre\customize\zipplugin.py", line 184, in load_module
  File "calibre_plugins.dedrm.kindlekey", line 189, in <module>
ModuleNotFoundError: No module named '_winreg'
DeDRM v7.0.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.34.0: Packaging C:\Users\Heather\AppData\Local\Temp\calibre_z38xszg1\ea3lwu49.kfx-zip
Processing container: B00ZEQMP8U_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\Heather\AppData\Local\Temp\calibre_z38xszg1\5xoshrgv_add_books\0\B00ZEQMP8U_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 533, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 218, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 261, in __init__
calibre_plugins.dedrm.mobidedrm.DrmException: Invalid file format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 626, in run
  File "calibre_plugins.dedrm.__init__", line 576, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B00ZEQMP8U_EBOK.azw has DRM and cannot be converted
```

**Comment by evildarkarchon** [comment] 2020-10-03 21:13
That looks like a similar (if not the exact same) error I had in issue #1262.

**Comment by tartley** [comment] 2020-10-20 21:25
Closing this as a duplicate of https://github.com/apprenticeharper/DeDRM_tools/issues/1262. Shout if that's not right.

**Closed by tartley** 2020-10-20 21:25 UTC
Labels: duplicate
