### ISSUE TITLE
Can't install DRM Plugin on Calibre

### ISSUE THREAD

**Issue by weyderfs** [apprenticeharper/DeDRM_tools#1192] opened 2020-08-06 21:24 UTC
```
calibre, version 4.99.4
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 4.99.4  embedded-python: False is64bit: True
Linux-5.4.0-42-generic-x86_64-with-glibc2.29 Linux ('64bit', 'ELF')
('Linux', '5.4.0-42-generic', '#46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020')
Python 3.8.2
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 319, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 200, in load
    reload(m)
  File "/usr/lib/calibre/polyglot/builtins.py", line 123, in reload
    return importlib.reload(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 602, in _exec
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 179, in load_module
    compiled = compile(code, 'calibre_plugins.%s.%s'%(plugin_name,
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

```
Calibre version: 4.2.2.0

**Comment by ElleKayEm** [comment] 2020-08-06 21:36
DeDRM is not compatible with Python 3 yet.  Use the non-beta release of calibre which has Python 2.

**Comment by marook** [comment] 2020-08-17 08:08
See #928 for more details.

**Comment by waterkip** [comment] 2020-08-23 22:52
> DeDRM is not compatible with Python 3 yet. Use the non-beta release of calibre which has Python 2.

FWIW Obok_plugin.zip does install on Python 3

**Comment by ElleKayEm** [comment] 2020-08-23 23:17
Really?  Can you share a log of a successful decryption?

**Comment by waterkip** [comment] 2020-08-23 23:40
I don't have a Kobo DRM book. But I tried installing it after the DeDRM_plugin.zip wouldn't install due to the error in this issue.

**Comment by NIV799** [comment] 2020-09-13 13:24
> calibre, version 4.99.4
> ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)
> 
> calibre 4.99.4  embedded-python: False is64bit: True
> Linux-5.4.0-7642-generic-x86_64-with-glibc2.29 Linux ('64bit', 'ELF')
> ('Linux', '5.4.0-7642-generic', '#46~1598628707~20.04~040157c-Ubuntu SMP Fri Aug 28 18:02:16 UTC ')
> Python 3.8.2
> Interface language: None
> Successfully initialized third party plugins: Obok DeDRM (6, 7, 0)
> Traceback (most recent call last):
>   File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 319, in add_plugin
>     plugin = add_plugin(path)
>   File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
>     plugin = load_plugin(path_to_zip_file)
>   File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
>     return loader.load(path_to_zip_file)
>   File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 200, in load
>     reload(m)
>   File "/usr/lib/calibre/polyglot/builtins.py", line 123, in reload
>     return importlib.reload(module)
>   File "/usr/lib/python3.8/importlib/__init__.py", line 169, in reload
>     _bootstrap._exec(spec, module)
>   File "<frozen importlib._bootstrap>", line 602, in _exec
>   File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 179, in load_module
>     compiled = compile(code, 'calibre_plugins.%s.%s'%(plugin_name,
>   File "calibre_plugins.dedrm.__init__", line 168
>     print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
>           ^
> SyntaxError: invalid syntax
> 

I am facing the same issue. May I know if there is a workaround/solution? Thanks

**Comment by ElleKayEm** [comment] 2020-09-13 13:31
Use the regular release of calibre.

**Comment by NIV799** [comment] 2020-09-13 15:46
> Use the regular release of calibre.

I am using the regular version. I install it via `sudo apt install calibre `
I am on calibre (calibre 4.99.4)

**Comment by ElleKayEm** [comment] 2020-09-13 15:59
That's a beta version with Python 3.  Current version is 4.23.  Available here:

https://calibre-ebook.com/

**Comment by tartley** [comment] 2020-10-21 02:52
Closing as a dupe of https://github.com/apprenticeharper/DeDRM_tools/issues/1324

**Closed by tartley** 2020-10-21 02:52 UTC
