### ISSUE TITLE
errori installing plugin on calibre v. 5.1

### ISSUE THREAD

**Issue by gcriaco** [apprenticeharper/DeDRM_tools#1278] opened 2020-10-02 16:53 UTC
syntaxerror: invalid syntax
![screen_20201002_185203](https://user-images.githubusercontent.com/52906999/94948918-68100d80-04e0-11eb-9eb1-0ddeab6dff39.jpg)

calibre, version 5.1.0
ERRORE: Eccezione non gestita: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.1 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Find Duplicates (1, 6, 2) && Generate Cover (1, 5, 11) && Kindle Collections (1, 7, 17) && Search The Internet (1, 7, 1) && User Category (1, 5, 2)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 200, in load
  File "site-packages\polyglot\builtins.py", line 123, in reload
  File "importlib\__init__.py", line 169, in reload
  File "<frozen importlib._bootstrap>", line 602, in _exec
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment] 2020-10-02 16:57
DeDRM is not compatible with calibre 5.x yet.  You'll need to use calibre 4.23 for now.

**Comment by tartley** [comment] 2020-10-06 15:07
If this issue is a straightforward Python2 to Python3 conversion, I could help. Is that useful?

**Comment by tartley** [comment] 2020-10-06 15:10
and, if I just do the syntax conversions in my own fork, is that likely to work?

**Comment by bmaupin** [comment] 2020-10-06 17:25
> DeDRM 6.8 is not compatible with calibre 5.x yet. You'll need to use calibre 4.23 for now.

For the lazy, this is how to downgrade on Linux (as per https://calibre-ebook.com/download_linux):

```
sudo -v && sudo calibre-uninstall && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin version=4.23.0
```

**Comment by chrvip** [comment] 2020-10-07 00:06
I  meet the bug too. I will try 4.23 , but hope to fix the bug asap.

**Comment by ElleKayEm** [comment] 2020-10-07 03:27
@tartley 
Feel free to help out.

**Comment by tartley** [comment] 2020-10-07 15:13
> Feel free to help out.

Thanks, good to know. Just to be explicit: I'm an experienced Python dev but know nothing about this project. If I just fork and start fixing Python3 syntax errors, then that is useful and not duplicating other people's work elsewhere?

**Comment by tartley** [comment] 2020-10-07 18:37
Am I wrong that:
* There are no tests
* Github actions runs pyflakes a couple of times, but that has been failing for a long time with lots of warnings
Let me know if I'm misunderstanding. Many thanks for helping me get up to speed.

**Comment by tartley** [comment] 2020-10-07 19:10
I have [a branch](https://github.com/apprenticeharper/DeDRM_tools/compare/master...tartley:python3-dedrm)

I'll try zipping it up and doing a spot check to see if it works in latest Calibre.
I guess I should also try using it from Calibre 4.23. It *ought* to work. We shall see.

This is probably a bigger question that I realize, but does anyone have hints on what I should try, other than convert a kindle book into an epub.

If all goes well, I'll create a PR for further discussion.

**Comment by daniele-athome** [comment] 2020-10-07 19:21
@tartley I've just downloaded your branch and tried with a couple of books (Adobe DRM) and it seems to be working. Thank you!!! I'll follow your progress.

**Comment by tartley** [comment] 2020-10-07 19:44
Thanks @daniele-athome . I concur: I have success converting three older AZW3 books, but fail in converting a newly released book that I bought yesterday, with log:
https://pastebin.com/EPTvSfxH (expires 7th Nov 2020)

Can anyone help me figure out whether that failure is due to my meddling, or perhaps due to it being a very new type of AZW3?

**Comment by tartley** [comment] 2020-10-07 20:05
My changes do not work on Python2, so don't work in Calibre 4.23.

I had misunderstood how 2to3 works. I thought it used 'six', so produced output that was compatible with both Python2 and Python3. That's wrong.

So I think I'll have to apply these changes manually, using the 'six' library, in order for it to work in all versions of calibre. Fortunately the 2to3 output gives us a roadmap of what needs to be changed. It's not hard, it's just a bunch of typing.

**Comment by tartley** [comment] 2020-10-07 20:12
But now I look at the recently merged PRs, I see people are not trying to maintain compatibility with Python2 (and older Calibre.) They are just converting to Python3 only. So I won't do the big manual edits with six.

**Comment by daniele-athome** [comment] 2020-10-07 20:15
> But now I look at the recently merged PRs, I see people are not trying to maintain compatibility with Python2 (and older Calibre.) They are just converting to Python3 only. So I won't do the big manual edits with six.

I agree, it's not worth it. I mean if you want to use Python 2 you can use Calibre 4 with DeDRM 6.8.0.

**Comment by tartley** [comment] 2020-10-07 20:33
I've confused myself. Reinstalling Calibre 5.2, I now find I can still convert my successful three AZW3 books even though I have apparently not got the DeDRM plugin installed. (I manually deleted the files from ~/.config/calibre/plugins, restarted Calibre, and don't see it listed in the plugins UI under "File Type".) So I guess that means my previous observed successes were on AZW3 files that don't actually have DRM? Can that be true?

Maybe I'm doing the conversion the wrong way. I've been converting format from AZW3 to epub or mobi. But I just read in the FAQ that the DRM-stripping takes place when a book is imported. Perhaps I did that to my AZW3 files in the past, and that's why they don't seem to have DRM now? I'll repeat my tests by re-importing the DRMed book...

**Comment by tartley** [comment] 2020-10-07 20:38
Re-importing my new book again, and then converting to epub, fails with the same DrmError described above no matter whether I'm using DeDRM from master, or my '2to3' version. It seems I've achieved nothing except confusing myself. :-)

**Comment by tartley** [comment] 2020-10-08 13:13
Instead of each of us bringing our own idiocyncratic test documents to convert, and getting different results for unknown reasons, is there a set of known test data which DeDRM should be able to convert?

I could use that to stimulate Python syntax errors in Calibre 5.2 with latest DeDRM, and see whether my branch fixes them? If it does, then it's useful and I would create a PR. If it does not, then it isn't useful and I should think some more.

Forgive me for speaking from ignorance but: Such a set of test data would be useful for everyone, not just me. Later, we could use it as the basis for an automated test.

**Comment by tartley** [comment] 2020-10-08 18:13
Created a PR to aid discussion and discoverability, even though I'm far from sure it should be merged yet.

**Comment by tartley** [comment] 2020-10-08 18:46
I have just discovered the instructions for adding Kindle keys to a Linux setup (at the bottom of https://github.com/apprenticeharper/DeDRM_tools/blob/master/DeDRM_plugin/DeDRM_Help.htm), which might explain the error described above on my one document from which I cannot remove DRM. I'll try again...

**Comment by akehir** [comment] 2020-10-09 20:48
@tartley nice work, I just used your branch as a zip file to remove the drm of a kindle azw3 (via serial number) on calibre 5.2, and it works beautifully.

**Comment by tartley** [comment] 2020-10-10 04:54
@akehir That's great to hear. Thanks for reporting it. I'm currently stalled on trying to run kindlekey.py (which itself needs converting to Python3) to get my kindle key so that I can verify this branch works.

I would run kindlekey.py on Python2, but it fails with syntax errors there too. Hmm, maybe fixing that syntax error will be an easier job than doing the whole Python3 conversion on it...

**Comment by tartley** [comment] 2020-10-20 21:24
Closing this issue as a duplicate of https://github.com/apprenticeharper/DeDRM_tools/issues/1324. Shout if that's not right.

**Closed by tartley** 2020-10-20 21:24 UTC

**Comment by ElleKayEm** [comment] 2020-11-19 14:35
> Instead of each of us bringing our own idiocyncratic test documents to convert, and getting different results for unknown reasons, is there a set of known DRMed documents which DeDRM should be able to convert?
> 
> I could use that to stimulate Python syntax errors in Calibre 5.2 with latest DeDRM, and see whether my branch fixes them. If it does, then my branch is useful and I would create a PR. If it does not, then my branch is not useful and I ought to understand why before proceeding.
> 
> Forgive me for speaking from ignorance but: Such a set of test data would be useful for everyone, not just me. Ideally it would contain one small document per DRM type, if that is a relevant thing? Later, we could use it as the basis for automated tests.

DeDRM works by using your own account details to unlock books so it would not be possible to have "test" DRM books.  The closest way to do this would be linking to freebies or very cheap books which are known to have DRM.  But often those are DRM-free already (also might disappear or change at any time).
