### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by Beaupedia** [apprenticeharper/DeDRM_tools#1310] opened 2020-10-13 05:13 UTC
Attempting to install the plugin and receive the following.

calibre, version 5.2.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Find Duplicates (1, 7, 2) && Goodreads Sync (1, 14, 3) && KePub Metadata Reader (3, 2, 9) && KePub Metadata Writer (3, 2, 12) && KePub Output (3, 2, 15) && KoboTouchExtended (3, 2, 15) && Quality Check (1, 10, 1)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 282, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 174, in exec_module
  File "calibre\customize\zipplugin.py", line 170, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by evildarkarchon** [comment] 2020-10-13 10:29
DeDRM hasn't been updated for calibre 5.x yet, it's still a work in progress.

**Comment by evildarkarchon** [comment] 2020-10-13 19:37
I have no idea, there are so many issues basically saying the same thing, I don't know which one is the primary.

**Comment by tartley** [comment] 2020-10-20 20:55
Closing as a dupe of https://github.com/apprenticeharper/DeDRM_tools/issues/1324

**Closed by tartley** 2020-10-20 20:55 UTC
Labels: duplicate

**Comment by ElleKayEm** [comment] 2020-10-20 21:12
I'd suggest following [Apprentice Alf's blog](https://apprenticealf.wordpress.com/).  There'll be a new post there when the next release of DeDRM comes out.
