### ISSUE TITLE
Cannot import dedrm plugin in calibre

### ISSUE THREAD

**Issue by LionKing668866** [apprenticeharper/DeDRM_tools#1280] opened 2020-10-03 13:19 UTC
Hi

My computer is mac air, catalina 10.15.7. I had installed python3.8.5 on my computer.

Several months ago, I had installded calibre previous edition and had imported dedrm plugin from files, it did work well.
I updated calibre three days ago to 5.1.0 by copied new edition to application instead of  older edition. After update, I found that dedrm plugin need to re-import again.

However, I encountered a big trouble. There was the same problem occured per I executed re-import.

Log as following:

`calibre, version 5.1.0
错误： 未处理的异常: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.1  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: zh_CN
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 472, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 61, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 202, in load
  File "lib/python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "site-packages/calibre/customize/zipplugin.py", line 179, in load_module
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax
`

Pls help me to solve this trouble. Any help will be appreciated.

**Comment by ElleKayEm** [comment] 2020-10-03 13:34
DeDRM is not compatible with calibre 5 yet.  For now you will need calibre 4.23 to run DeDRM.

**Comment by LionKing668866** [comment] 2020-10-04 02:47
> DeDRM is not compatible with calibre 5 yet. For now you will need calibre 4.23 to run DeDRM.

@ElleKayEm 

Thank you for your help.
I reinstalled calibre 4.23, dedrm did imported.

However, it did not work well. I selected a .azw3 book, but I could not transfer it to .mobi and even I could not open it.

How I can do next?

**Comment by ElleKayEm** [comment] 2020-10-04 08:46
Post a log of adding the book:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by vimy100** [comment] 2020-10-05 05:41
@ElleKayEm

"DeDRM is not compatible with calibre 5 yet. For now you will need calibre 4.23 to run DeDRM."

Must I remove calibre 5.1 before installing 4.23 and if 5.1 must be removed, will that affect my calibre library?

**Comment by ElleKayEm** [comment] 2020-10-05 12:02
@vimy100 
I believe you can downgrade in the same way that one upgrades calibre by installing without needing uninstall first.  But I'm no calibre expert.  Either way your library will remain in place.  If you're on Windows, I've seen people suggest installing calibre portable 4.23 for DeDRM and continuing to upgrade their main installation of calibre.

**Comment by vimy100** [comment] 2020-10-05 12:06
Thanks, ElleKayEm.  I'll give that a try.

**Comment by calmeilles** [comment] 2020-10-06 00:04
Have you a timescale for an update?

Just wondering whether better to downgrade Calibre or wait for a DeDRM release.

**Comment by ElleKayEm** [comment] 2020-10-06 00:23
@calmeilles 
There's really no telling.  This is an all volunteer, as time allows, community project.  Work has been going on for a while.  Things have picked up with the release of calibre 5, but it's still going to take as long as it takes.

I'm just going to stay on calibre 4.23 myself.  There's nothing in calibre 5 that's more important to me than having working DeDRM.

**Comment by calmeilles** [comment] 2020-10-06 00:30
Thank you.  It took me about 10 minutes and a new book to come to the same conclusion.  :)  And the downgrade is easy for Linux at least:
`sudo -v && sudo calibre-uninstall && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin version=4.23.0`

But I _will_ be glad (and grateful) when things can sync at the latest vers again, one less thing to have to keep an eye on.

**Comment by khoanguyen0791** [comment] 2020-10-07 04:57
All the `print` statements use the syntax of python 2 (PEP 3105 specification) while the reference version is python 3.8. 
A simple fix will be to use `print` with parentheses. 

[Python Print](https://docs.python.org/3/whatsnew/3.0.html)

**Comment by sturgman** [comment] 2020-10-07 14:52
I installed 5.X and then uninstalled it and replaced it with 4.23. When I try to load the plugin I get:
```
calibre, version 4.23.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'C:\\Users\\user\\Downloads\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 194, in load
  File "site-packages\calibre\customize\zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'C:\\Users\\user\\Downloads\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file
```

**Comment by tartley** [comment] 2020-10-08 18:33
One such branch already exists: https://github.com/apprenticeharper/DeDRM_tools/pull/1292

**Comment by tartley** [comment] 2020-10-20 21:24
Closing this issue as a duplicate of https://github.com/apprenticeharper/DeDRM_tools/issues/1324. Shout if that's not right.

**Closed by tartley** 2020-10-20 21:24 UTC
